### ISSUE TITLE
A new proxy can be added without filling up mandatory information for URL and Elastic Search

### ISSUE THREAD

**Issue by Nazarah** [Digipalvelutehdas/APIKA#104]
# Reproduction step
1. sign in as APINF admin.
2. Go to profile->Proxy
3. Click Add proxy
4. 1st select proxy type without filling other fields. (mandatory fields don't get populate after selecting proxy type)
5. Fill up name and description and save.

# Result:
Proxy can be added without filling mandatory fields (elastic search and URL).
This behavior doesn't occur if fields are filled serially.
![proxy](https://cloud.githubusercontent.com/assets/17976243/21002920/fcec144a-bd30-11e6-8d21-d2e3439b1e14.gif)

# Expected Result:
no matter what order the fields are filled up, on selecting a proxy from the dropmenu, the mandatory fields should appear in the instant.

**Comment by jykae** [comment]
@preriasusi you are famous video actor :D

**Comment by bajiat** [comment]
@marla-singer Can we move this issue to In progress column?

**Comment by marla-singer** [comment]
@bajiat sure
