### ISSUE TITLE
Delete API 'Dashboard' text not updated

### ISSUE THREAD

**Issue by saralavanip** [Digipalvelutehdas/APIKA#106]
# Steps 
1. Visit https://staging.apinf.io  
2. Sign up 
3. Add  API without proxy   
4. Go to 'Settings' 
5. Delete the above added API 
6. Go to 'Dashboard' view  

# Expected Result 
Dashboard text must be updated notifying user 'No APIs to Manage, Add API'  

# Actual Result  
-  Dashboard text not updated 
-  Displays text from previous state ' You have not yet connected your API to a proxy'  

# Screenshot   
![delete_api_dashboard_text_not_updated](https://cloud.githubusercontent.com/assets/13309358/21004177/bca1ccd4-bd37-11e6-99b2-906fadb8920b.PNG)

**Comment by marla-singer** [comment]
@bajiat Verified it on current develop branch and it reproduces as well
