### ISSUE TITLE
Create a full CRUD REST API for all collections

### ISSUE THREAD

**Issue by brylie** [Digipalvelutehdas/APIKA#107]
Start building our REST API by adding the minimum REST API for all collections. Our REST package gives us a full CRUD API with just a few lines, so lets start there. More specific, composite endpoints can be added as needed.

Related issue #15 

# Definition of done
* [ ] REST endpoint exists for all collections
  * [ ] Each endpoint supports common HTTP verbs (e.g. GET, PUT, POST, DELETE)
* [ ] REST endpoints share collection permissions, for security
* [ ] REST endpoints use some form of authentication

**Comment by jykae** [comment]
@brylie collection allow/deny has been discussed, though not available yet https://github.com/kahmali/meteor-restivus/issues/163
However role-based permissions exist, https://github.com/kahmali/meteor-restivus#rolerequired

Related issues: #108 #109 #110

**Comment by brylie** [comment]
OK, role-based is fine for now, for Admin role only. We need to figure out how to do more granular permissions. E.g. how can we allow an Organization or API manager to edit their API via REST?

**Comment by bajiat** [comment]
This issue was moved to apinf/platform#2060
