### ISSUE TITLE
Research how to integrate Apika with EMQ

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/APIKA#124]
Clarify how an MQTT API can be connected to eMQ broker / proxy via APIKA. REST APIs are connected to proxy (e.g. API Umbrella) through an internal Admin API. Determine the options for connecting the MQTT API.

# Definition of done
* [ ] Look into options for connecting the API
* [ ] Select the most reasonable option
* [ ] Document the options and the recommendation

**Comment by brylie** [comment]
At first glance, there seem to be several related EMQ components here:

- [HTTP Publish API](http://emqtt.io/docs/v2/guide.html#http-publish-api) - HTTP API for publishing messages to MQTT channels
- [username/password auth](http://emqtt.io/docs/v2/guide.html#username-password) - required by HTTP Publish API and ACL
- [ACL](http://emqtt.io/docs/v2/guide.html#acl) - rules to allow MQTT clients to publish/subscribe topics
  - [ACL HTTP API](http://emqtt.io/docs/v2/guide.html#http-api) - allows us to configure ACL rules via HTTP

**Comment by brylie** [comment]
A high-level goal might be described as **"create a REST API for `emqttd_ctl`"**.

- [emqttd_ctl commands](http://emqtt.io/docs/v2/commands.html)

**Comment by brylie** [comment]
I opened an [upstream issue](https://github.com/emqtt/emqttd/issues/820) to get support and/or feedback for this idea.

**Comment by bajiat** [comment]
Let's create an issue to test adding a user and access control rule a particular topic
