### ISSUE TITLE
Modify API profile LAF

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/APIKA#129]
The request for APIKA has been to have a API profile thatt does not use so many tabs, but rather utilises blocks of information. Designed in #83.

**Comment by jykae** [comment]
@bajiat I suppose we mean "Look & Feel" with LAF here in context of UI design. 
Although it has many meanings http://www.urbandictionary.com/define.php?term=laf

**Comment by bajiat** [comment]
This issue was moved to apinf/platform#2066
