### ISSUE TITLE
Generate sdks for the one with swagger

### ISSUE THREAD

**Issue by kyyberi** [Digipalvelutehdas/APIKA#13]
As api owner I would like to have generated sdks for my apis. At least I should have ability add them to my api profile if I choose to use this opportunity. In addition sdks should be synced to github repo chosen by me. in fact sdks should be generated to github directly. If swagger is changed and new sdks should be generated, I should be offered that and warned that old sdks are overwritten.

**Comment by kyyberi** [comment]
We must find ways to encourage api developers to use api specs with development. Creating added value for doing so will boost usage of swagger and alike tools.

**Comment by bajiat** [comment]
SW supports the SDK, but it requires enabling Codegenerator in Settings and providing a link to a service that is running Codegen.
