### ISSUE TITLE
Allow organization managers to define organization contact person

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/APIKA#131]
At the moment, organization contact person can only be added when organization is added. There is no option to modify the contact person. 

Allow organization managers and admins to define the organization contact person.

Proposal 1: free text: name, phone number or email
Proposal 2: Select one of the organization managers as contact person. Extend the current user profile to contain full name and phone number.  Profile should also have privacy setting for contact information like phone number and email. Whatever has been entered to profile and is public is shown on the organization page.

# Definition of done
* [x] Organization manager can add a contact person for organization (either in organization settings or inline in the organization profile main view).
* [x] Organization manager can give the following information for the contact person: name, email, phone nr.
* [x] Organization contact person information is displayed on the organization profile.
* [x] Organization manager can edit and delete any of the details for the contact person.

# Wireframe
1. Inline editing option
on mouse hovering near the contact information pane, an edit button appears
![contactpersonsettings](https://cloud.githubusercontent.com/assets/17976243/21336673/bf1b8270-c66f-11e6-8dee-5ffaa0605203.png)

On clicking the button, the fields become editable and changed can be saved/discarded using the Save and Cancel button
![contactpersonsettings2](https://cloud.githubusercontent.com/assets/17976243/21336693/e60bef28-c66f-11e6-8c31-2bd20dd40f84.png)

2. If a tab view of organization is considered, then we can simply place fields for adding contact information for an organization there.
![altorganizationprofilesettings](https://cloud.githubusercontent.com/assets/17976243/21336755/3e9680c2-c670-11e6-9177-d4a1c37e3443.png)

**Comment by bajiat** [comment]
Estimation is for free text.

**Comment by Nazarah** [comment]
@bajiat @brylie please give your feedback about the wireframes

**Comment by bajiat** [comment]
@Nazarah Where can I see the wireframe?

**Comment by Nazarah** [comment]
@bajiat for some reason, the upload was not completed, yet in preview the wireframes appeared. I am readding them. sorry for the mishap.

**Comment by brylie** [comment]
The mockups look good.
