### ISSUE TITLE
Organization managers inherit API manager rights for connected APIs

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/APIKA#133]
When an API gets connected to an organization, each of the organization managers for that particular organization should inherit API manager rights for any APIs that are connected to the organization. 

# Definition of done
* [ ] An organization manager has the same rights as the original API manager to edit, delete the API after an API has been connected to an organization.

**Comment by marla-singer** [comment]
@baijat Interested

**Comment by bajiat** [comment]
@nnn Could you take this task, since this is almost direct continuation to your task with organization mgrs?
