### ISSUE TITLE
Show nr of connected APIs in organization card

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/APIKA#134]
The below left corner of organization card should display and indicator the number of connected APIs for each organization.

If possible,  use the same implementation and style to show the number of connected APIs on the organization profile. Size of indicator could  scaled up for the profile page. 

# User story
> As an organization manager, I want to show the number of connected APIs per organization
so that it makes my organization more appealing to developers.

# Definition of done
* [ ] There is a number and an icon representing the amount of connected APIs in the below left corner of organization card.
* [ ] If possible, there is a number and an icon representing the amount of connected APIs on organization profile page.

# Wireframe

Organization Card
![organizationcard](https://cloud.githubusercontent.com/assets/17976243/21337074/d2e2abdc-c672-11e6-98de-5d5004ba2589.png)

In Organization Profile
The no. of APIs connected to the organization appears on the header of organization profile.
Between organization URL and Contact information.
In this way, user can always see no. of APIs connected if s/he switches between tabs (in the case tab design is implemented)
![connectedapis](https://cloud.githubusercontent.com/assets/17976243/21350072/16e0c940-c6be-11e6-8923-4918b9da58af.png)

**Comment by marla-singer** [comment]
Interested

**Comment by Nazarah** [comment]
@bajiat @marla-singer consider the scenario in Organization profile
When you first view it, you see the number of APIs
![contactpersonsettings](https://cloud.githubusercontent.com/assets/17976243/21308913/b6ca8502-c5e4-11e6-96e0-171eea2470a3.png)
However, when filtering option in the organization page will be implemented, a filtering result would change the number of APIs displayed. These would be mentioned that the result is being filtered.
![altorganizationprofileapifilter3](https://cloud.githubusercontent.com/assets/17976243/21308981/f7340d34-c5e4-11e6-8f49-05136495f03b.png)

Should we consider implementing this option here as well?
What changes would you like to suggest here?

**Comment by bajiat** [comment]
@Nazarah 

Maybe the number for APIs could be in the organization information together with logo, name, contact person? In that case, it could be the total number of APIs, rather than than total number of APIs shown/filtered currently?

Please also note that the request was to show a similar icon for the page as for the card in organization catalog., i.e. share the implementation.

**Comment by Nazarah** [comment]
@bajiat please have a look at this one. Would it suffice? This way user will always get to see the number of connected APIs regardless wherever s/he is in the organization profile.
![connectedapis](https://cloud.githubusercontent.com/assets/17976243/21337122/309a5c2a-c673-11e6-92e3-b194f954289c.png)

**Comment by jykae** [comment]
@Nazarah @bajiat proposing textual presentation "APIs" instead of "</>" to card. 
imho "</>" does not associate well with API.

**Comment by bajiat** [comment]
@jykae @nazarah Is there any other image we could use to represent API. How about: {A}
