### ISSUE TITLE
Modify top bar links to Organization and API catalogs

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/APIKA#135]
The API catalog should be directly accessible from top bar instead of accessing it through Catalog and then selecting APIs. Include APIs and Organizations as links to top bar as links to the relevant Catalogs. Note that APIs should come first.

# Wireframe

Picture of the new top bar that houses both API Catalog and Organization Catalog as separate links.
API catalog comes first, then Organization Catalog
![newtopbar](https://cloud.githubusercontent.com/assets/17976243/21222935/37dcdae8-c2cd-11e6-9d76-09dd353e2ef8.png)

**Comment by marla-singer** [comment]
@bajiat Like this ?
![joxi_screenshot_1481705686911](https://cloud.githubusercontent.com/assets/20643403/21175594/2d58ddd0-c1f4-11e6-89d1-24ad4a798748.png)

**Comment by marla-singer** [comment]
@bajiat Can I take it on work?

**Comment by Nazarah** [comment]
@marla-singer : Let me give you the picture I designed for

**Comment by bajiat** [comment]
@marla-singer Yes, you can take this. Just use "APIs" instead of "APIs catalog".
