### ISSUE TITLE
Change API proxy not updating 'API URL' in Details view

### ISSUE THREAD

**Issue by saralavanip** [Digipalvelutehdas/APIKA#138]
# Steps  
1. Visit https://staging.apinf.io 
2. Login as admin 
3. Go to 'Proxies' 
4. Add multiple proxies and save (eg. proxy 1 , proxy 2)
5. Sign out 
6. Sign Up / Sign In as owner 
7. Add API (eg. API 1) with proxy (eg. proxy 1)
8. Go to API view and click on 'Proxy' 
9. Select 'proxy 2' from drop down menu 
10. Confirm clicking on 'Change API proxy' button   

# Findings  
- API URL in 'Details' view not updated  
- User not notified with successful message
- Clicking on 'Save&Publish' button not working

**Comment by jykae** [comment]
Interested

**Comment by bajiat** [comment]
@jykae Assigned you. Please estimate.

**Comment by jykae** [comment]
@bajiat This is probably related to bigger proxy changing issue last year, and might be fixed. Verifying..

**Comment by jykae** [comment]
@bajiat Tested with latest develop. Details are updated, changed from nightly Umbrella to staging Umbrella. "Change API proxy" button is not triggering proxy change but "Save & Publish" button after that. Save & Publish works & shows message on success.

**Comment by jykae** [comment]
@saralavanip @bajiat Tested also on staging. Works. Proposing issue to be closed.

**Comment by bajiat** [comment]
@saralavanip Can you verify that this issue can be closed?

**Comment by saralavanip** [comment]
@bajiat , @jykae  , verified this issue on https://staging.apinf.io version 0.38.1 
Findings: 
- Change Proxy from (staging: API umbrella)  to another proxy (nightly: Nightly umbrella) displays error 'Cannot read property 'length' null  

Screenshot 1: Currently have these proxies on staging 
![staging_proxy](https://cloud.githubusercontent.com/assets/13309358/22145857/98c05de4-df0b-11e6-98e8-71d57e3bd22f.PNG)

**Comment by bajiat** [comment]
Verification blocked by #267.

**Comment by marla-singer** [comment]
@saralavanip @bajiat The server has correct settings. Please try again. On my side, it works as expected

**Comment by saralavanip** [comment]
@bajiat , @marla-singer , verified this resolved issue on https://staging.apinf.io version 0.39.0 and it is not reproducible.

**Comment by bajiat** [comment]
Closing as resolved.
