### ISSUE TITLE
'Add organization' as admin doesn't notify user with successful message

### ISSUE THREAD

**Issue by saralavanip** [Digipalvelutehdas/APIKA#139]
# Steps  
1. Visit https://staging.apinf.io  
2. Login as admin 
3. Click on 'Add Organization'  
4. Fill the form with all the required details  
5. Click on 'Create Organization' button  

# Expected Result  
- Notify user with successful message  

# Actual Result 
- User not notified with successful message

**Comment by marla-singer** [comment]
@bajiat It's really simple to fix. Can I take it on work?

**Comment by bajiat** [comment]
@marla-singer Yes, sure, go ahead.

**Comment by saralavanip** [comment]
@bajiat , verified this resolved issue and it is not repeoducible.
