### ISSUE TITLE
Organization catalog not available for users

### ISSUE THREAD

**Issue by saralavanip** [Digipalvelutehdas/APIKA#140]
# Steps  
1. Visit https://staging.apinf.io  
2. Login as admin 
3. Click on 'Add Organization'  
4. Fill the form with all the required details  
5. Click on 'Create Organization' button  
6. Go to Catalog 

# Expected Result  
-  Organization catalog available for users

# Actual Result 
- Organization catalog not available for users

**Comment by bajiat** [comment]
@saralavanip Can you add the release nr from About in all your bug reports from now on?

Organization catalog was not implemented yet. Closing the issue.

**Comment by saralavanip** [comment]
@bajiat , OK! Sure, I'll add the release number .
