### ISSUE TITLE
Admin Dashboard:'Select API' list not segregated

### ISSUE THREAD

**Issue by saralavanip** [Digipalvelutehdas/APIKA#150]
# Steps  
1. Visit https://staging.apinf.io  
2. Login as admin  
3. Navigate to'Dashboard ' 
4. Click on 'Select API' drop down menu   

# Expected Result  
Show the segregated list of APIs: 'Admin APIs','My APIs' and 'Other'   

# Actual Result  
API list not segregated. It shows all APIs as 'My APIs'   

# Screenshot 
![dashboard_only_myapis_list](https://cloud.githubusercontent.com/assets/13309358/21222245/a49ccd68-c2c9-11e6-9924-45090a885a93.PNG)

**Comment by bajiat** [comment]
This issue was moved to apinf/platform#2042
