### ISSUE TITLE
Remove organization from Add API form

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/APIKA#157]
We would like to separate adding an API and connecting an API to an organization. This would keep the Add API form as simple as possible and not confuse API owners who are not affiliated with any organization.

# Definition of done
* [x] There is no option / field for adding an organization in the Add API form

**Comment by jykae** [comment]
Interested

**Comment by bajiat** [comment]
@jykae This is related to your schema task. Please estimate.

**Comment by saralavanip** [comment]
@bajiat , verified this resolved issue on https://staging.apinf.io version 0.38.0
