### ISSUE TITLE
Connect API to an organization from API settings

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/APIKA#158]
If the current user is both organization manager and the owner of current API, the user needs to be able to connect the current API to an organization the user is managing. API settings should contain a field to connect API to organization and that field should only be conditionally available.

# Definition of done
* [x] An API owner can see a Connect API to an organization setting in Settings tab, if he also has the role of organization manager
* [x] The available choices for organizations to connect to are organization(s) the current user manages
* [x] If the user selects and organization and saves the changes, a connection between API and organization is made

# Wireframes
1. From API profile's settings tab, API manager can see a dropmenu that contains organizations that s/he manages. API manager can select one of the organization to connect her/his API to it. The dropmenu appears under Details pane.
![apisettings1](https://cloud.githubusercontent.com/assets/17976243/21383955/ea6a44b4-c770-11e6-97b8-6f67cfd6c00f.png)
The following text should appear below the dropmeu (sorry not included in the wireframe).
You can connect your API to one of the organizations that you manage. Afterwards your API will appear in the organization profile. You can connect your API to only one organization only.

2. On selecting an organization and clicking Save, API manager gets an S-alert informing that the API is now connected to the organization and s/he can view the API in the organization profile.
![apisettingsadmin](https://cloud.githubusercontent.com/assets/17976243/21384066/6ae0a624-c771-11e6-809c-cf7d76217eaa.png)

**Comment by marla-singer** [comment]
Interested

**Comment by bajiat** [comment]
Please estimate

**Comment by marla-singer** [comment]
@bajiat Done.

**Comment by Nazarah** [comment]
@marla-singer @bajiat let me know your feedback about the wireframes.

**Comment by bajiat** [comment]
@Nazarah Where can I find the wireframes for this flow (no suggestion + approval)?

**Comment by brylie** [comment]
@marla-singer please see discussion in issue #160. We haven't fully decided how to relate organizations and APIs, i.e. what relationship type to use. We need to arrive at a group decision before going further with this task.

**Comment by marla-singer** [comment]
@brylie Well, so when will question about schema be resolved?

**Comment by brylie** [comment]
You can contribute your thoughts in the discussion. We will try to reach a consensus in the next day or so.

**Comment by bajiat** [comment]
@Nazarah Wireframes look ok. You may want to rephrase the text below the dropdown menu: "You can connect your API to *only* one organization *only*."
