### ISSUE TITLE
Modify schemas for API and organization relationship

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/APIKA#160]
The API collection/schema should not contain the organization id, because that would make organization a mandatory feature. Additionally, it could make a potential enhancement - suggesting APIs to a connection - more difficult to implement.

Consider a joint schema for the connection or move API id to organization collection.

# Possible relationships
Based on discussion between @bajiat and @brylie, we identified four common/possible relationship types:

![screenshot_20161219_142130](https://cloud.githubusercontent.com/assets/17307/21312740/9480553c-c5f6-11e6-85b6-ae75e2d62834.png)

- a: the `Organizations` collection contains an array field of `apiIds`
  - an Organization may have multiple APIs
- b: the `Apis` collection contains a **String** field for a single `organizationId`
  - an API belongs to one organization
- c: both the `Organizations` and `Apis` collections contain fields described above
- d: there exists an intermediary collection `OrganizationApis` that contains fields for `organizationId` and `apiIds`, as well as possibly other metadata
   - additional metadata might include fields for an approval process

# Definition of done
* [ ] Sketch a diagram for collection options for organization and API relationship
* [ ] Choose the one that would allow
  * [ ] suggestion flow
  * [ ] possibly making organization an optional feature later
* [x] Make the required changes to schemas, possibly adding a new collection

**Comment by jykae** [comment]
Interested

**Comment by bajiat** [comment]
@jykae Please estimate

**Comment by marla-singer** [comment]
@jykae I think my tasks #158 #159 depend on your schema. When are you going to start this task? I'd like to see a diagram sketch

**Comment by bajiat** [comment]
@brylie Can you share the diagram(s) we sketched on the whiteboard?

**Comment by brylie** [comment]
@bajiat I added the **Possible relationships** section to the issue description.

**Comment by bajiat** [comment]
thanks @brylie

**Comment by bajiat** [comment]
@brylie @jykae @marla-singer In my opinion, the option D would give us the ultimate flexibility for connecting apis and organizations. Also, it would allow for organizations being an optional module, if we later decide to make it one.

**Comment by marla-singer** [comment]
As for me **A** and **B** cases  are not enogh for us. We have dual-sided connection between Organization and APIs collections. The **C** case is obviously solution. And yes, maybe **D** case would give us the flexibility in future but it'd be also hard to implement

**Comment by brylie** [comment]
For option **d**, implementation would be something like this:

- create a collection to for the relationship, e.g. `OrganizationApis`
- create a basic schema for the collection
  - `organizationId`: *String*
  - `apiIds`: *Array* of *String*
- UI component from Organization and API profile views, shared code
  - Modal dialogue
  - AutoForm for `OrganizationApis` collection (insert and update)
    - If `organizationId` is passed in, hide and auto-value the `organizationId` field
    - If `apiId` is passed in, hide `apiIds` field and 
        - [$push](https://docs.mongodb.com/manual/reference/operator/update/push/) the `apiId`to the `apiIds` field

**Comment by philippeluickx** [comment]
Definitely leaning towards option D. @marla-singer what would be the main challenges for this implementation?

We could start naming them as integration? E.g. Organization-Api-Integration package.

**Comment by marla-singer** [comment]
@philippeluickx I don't know. Can't see the overall picture and have a lot of question. Hope it will bemore clear after realization

**Comment by philippeluickx** [comment]
Fair concerns and I do agree complexity will be higher. Considerig the modularity we try to achieve, it's pretty much the only option I can see work in the long run though.

**Comment by brylie** [comment]
@marla-singer for some additional context, we are working to break our project into modules, so that we can publish them to NPM. This would mean that an Apinf deployment, such as Apika, could pick the modules that were suitable for their needs. To work towards this goal, we are [discussing how to architect our code as a collection of modules, with a module management UI](https://github.com/apinf/platform/issues/1970).
