### ISSUE TITLE
Test normal deployment conditions for ElasticSearch

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/APIKA#164]
Ensure that we can get analytics data for APIKA, apinf.io and staging, where ElasticSearch is not exposed by public HTTP

**Comment by bajiat** [comment]
@shaliko Could you clarify how we are getting the Elastic Data in each deployment?

**Comment by shaliko** [comment]
@bajiat "APIKA, apinf.io and staging" that question more for Platform developers. Based on code that was shared by @brylie Meteor app (backend side) directly connect to "ElasticSearch" https://github.com/Digipalvelutehdas/APIKA/blob/develop/dashboard/server/methods.js#L27.

In our docker-compose deployment config, ElasticSearch works in separate docker container that not public and connection to it available only from "Platform" and "Umbrella" containers.

"Platform" fetching data from ElasticSearch for show it on dashboard (charts).
"Umbrella" store data to ElasticSearch from proxy and fetching data for show it on dashboard (umbrella admin charts).

I split ElasticSearch to separate container for:

1) Upgrade it to version 2.
2) Allow deploy it to separate server if we will need it in future.
3) Easy update ElasticSearch version without need restart or stop Umbrella.
4) Easy migrate on more higher performance server if ElasticSearch will be bottle neck.

https://github.com/apinf/platform/pull/1537
