### ISSUE TITLE
Change proxy and Call API doesn't update data on 'Dashboard'

### ISSUE THREAD

**Issue by saralavanip** [Digipalvelutehdas/APIKA#165]
# Steps  
1. Visit https://staging.apinf.io 
2. Login as admin 
3. Go to 'Proxies' 
4. Add multiple proxies and save (eg. proxy 1 , proxy 2)
5. Sign out 
6. Sign Up 
7. Add API (eg. API 1) with proxy (eg. proxy 1)  
8. Get API key  and call API  
9. Go to API view and click on 'Proxy' 
9. Select 'proxy 2' from drop down menu 
10. Confirm clicking on 'Change API proxy' button   
11. Get API key and call API  
12. Go to Dashboard  and select the above API  

# Findings  
- Changing the API proxy and calling API doesn't  show any data on dashboard.

**Comment by bajiat** [comment]
@saralavanip Can you check whether this bug can be reproduced on staging?

**Comment by saralavanip** [comment]
@bajiat , verified this issue on https://staging.apinf.io version 0.38.1 , reported related issue #268

**Comment by marla-singer** [comment]
@saralavanip @bajiat The server has correct settings. Please try again. On my side, it works as expected

**Comment by marla-singer** [comment]
@saralavanip @bajiat The server has correct settings. Please try again.

**Comment by bajiat** [comment]
@saralavanip I suggest that this issue should be closed now. Any comments from you?

**Comment by saralavanip** [comment]
@bajiat ,  Yes we can close this issue and also we need to note that the smallest time interval in the dashboard timeline could be approximately one hour.
