### ISSUE TITLE
Anonymous user can't see any Organization profile

### ISSUE THREAD

**Issue by marla-singer** [Digipalvelutehdas/APIKA#169]
Anonymous user can't see any Organization profile, looks like the empty page.
### Steps
1. Go to nightly.apinf.io
2. Sign out if you was sign in
3. Navigate to Organizations Catalog
4. Select any organizations

### Found
Empty page without information about organization

### Expected
Any user can see organization profile

**Comment by bajiat** [comment]
@marla-singer Could you add Steps to reproduce, Expected result and Actual result?

**Comment by marla-singer** [comment]
@bajiat Done

**Comment by kyyberi** [comment]
Confirmed, I get the same result.

**Comment by bajiat** [comment]
@brylie Check what is the situation with the issue. Was this fixed in another PR?

**Comment by brylie** [comment]
This bug seems to be resolved with the recent re-write of the Organization Profile. Please verify in nightly.

/cc @bajiat

**Comment by bajiat** [comment]
Verified in nightly using the steps to reproduce. Result; Anonymous user can view an organization profile. Closing the issue.
