### ISSUE TITLE
Filter APIs by lifecycle status in API catalog

### ISSUE THREAD

**Issue by brylie** [Digipalvelutehdas/APIKA#170]
Once the API Lifecycle Status feature is working, we want to allow users to filter by lifecycle status when browsing the API catalog.

This issue is a placeholder for further discussion, and will be updated when we are closer to working on the task.

# Wireframes

1. API filtering from API catalog
![apicatalognew2](https://cloud.githubusercontent.com/assets/17976243/21539093/f64b59f8-cdab-11e6-8254-928e2d8f6ede.png)

![apicatalognew2](https://cloud.githubusercontent.com/assets/17976243/21539096/fc208358-cdab-11e6-99b9-f7b4bde400d1.png)

![apicatalognew3](https://cloud.githubusercontent.com/assets/17976243/21539120/4a3cb84a-cdac-11e6-8a04-8839952e70c5.png)

![apicatalognew4](https://cloud.githubusercontent.com/assets/17976243/21539128/50b7b666-cdac-11e6-8d9a-4a65651eb465.png)

**Comment by philippeluickx** [comment]
Should we filter out deprecated APIs by default? How can we give a clear visual hint of this then?

**Comment by philippeluickx** [comment]
I assume when placing multiple values, the filter should be "OR".

**Comment by philippeluickx** [comment]
What are the usecases for filtering? When would someone want to filter for anything except the "Live - production" APIs?

**Comment by bajiat** [comment]
See related issue #8 

Are these potential use cases for filtering of other that production apis: 
* design: you would like to comment already at the design phase
* testing: you want to see what is coming

**Comment by bajiat** [comment]
@marla-singer Could you take this task? You should be reusing filter component from Organization filter.

**Comment by marla-singer** [comment]
@baijat Yep

**Comment by bajiat** [comment]
Please estimate

**Comment by marla-singer** [comment]
Done
