### ISSUE TITLE
Lifecycle status info for API

### ISSUE THREAD

**Issue by TuulaP** [Digipalvelutehdas/APIKA#18]
As an API user, I would like to see which APIs are in design, prototype, stable or ramped down . The status helps me to select the most appropriate API for a purpose.

(Bit related to #7 for the API owner & #15  to allow adding already design phase APIs as they are being developed.)

**Comment by bajiat** [comment]
@TuulaP Are you looking for a predefined list of API statuses? How would you like end users to browse for status?

**Comment by TuulaP** [comment]
Yes, I'm thinking some kind of filtering to see, which APIs are 'stable', which are 'in development'  (which one could give or ask input depending on viewpoint), which are 'in testing' and would benefit some experimenting and so forth.  Or if API is 'deprecated' for any reason and it is recommended to use a new version etc.

**Comment by Nazarah** [comment]
@TuulaP Hei. I have a few questions about the API lifecycle.
1. do you wish to select a life cycle phase when adding a new API? would it be a mandatory field? Would there be certain restriction about what phase can be selected when you are adding a new API
2. would you like to see the lifecyle status of an API in API list page?
3. In organization view, would you like to see API list appearing categorized by the life cycle phases?
4. In API profile would you like to have a view on which phase the API is currently now and what were the past phases and what would be the future phases?
5. What are your feedback about the following phases?
* Design and Prototyping
* Development
* Testing
* Stable
* Deprecated
Would you like to add any more phases here?
6. Suppose you have two versions of the same API. The older version is kept for backward compatibility. Should it be in Stable version?

**Comment by kyyberi** [comment]
For "Would there be certain restriction about what phase can be selected when you are adding a new API" I would say that "deprecated" is not an option.

**Comment by philippeluickx** [comment]
I presume this is linked to API versioning? So you could have a v1 that is deprecated, a v2 that is stable and a v3 in development?
Should these versions be linked through lifecycle status?

**Comment by TuulaP** [comment]
@philippeluickx Good point, yes. Usually API offerers add this info to the documentation e.g. FB have list of their [Graph API versions](https://developers.facebook.com/docs/apps/versions) with specific logic of advancing API versions and onwards in the lifecycle. But some are bit brief with this information, so choosing the 'correct one' is bit tricky.

@Nazarah Yes, since as an API creator that would be nifty way to describe our incoming workflow. As an API user seeing the what is coming from the organisation which I'm interested would help too. 

> would you like to see the lifecyle status of an API in API list page?

Yes, in API list it would be useful (or having a filter to select lifecycles in different states). Give me all stable ones. Or I'm feeling helpful, show me all that are in design phase. 

> In organization view, would you like to see API list appearing categorized by the life cycle phases?

Hmmm, yes. Sorted by life cycle, that could give useful way to the situation of one organization.

> In API profile would you like to have a view on which phase the API is currently now and what were the past phases and what would be the future phases?

Hmm, not necessarily. This would be most useful to see the "change dates", i.e. when an API has changed from one status to another, e.g. if there is only one version and apps of the developers start to break - then the lifecycle history might give insight for the developer about what has happened.


>What are your feedback about the following phases?  Design and Prototyping, Development, Testing, Stable, Deprecated

Sound good. Testing could also be QA to indicate that there could be joint QA period to check out the API with some others than API creator side, to smooth out any possible weirdnesses. Not too many in any case as some might jump to the 'Stable' without the earlier ones. 

Deprecated - is this status of an API which still might be working until a server dies with no guarantees from the API creator. Or this is the moment that API has been shutdown and cannot be used anymore? (Not that it would happen often, though, if all goes well.)

> Suppose you have two versions of the same API. The older version is kept for backward compatibility. Should it be in Stable version?

Yes - then API user can decide, which she uses, - maybe there is some suitable module for the old version but not for the new one etc.

**Comment by Nazarah** [comment]
@TuulaP I've made some low fidelity sketches about the idea of API life cycles. Please give me your feedback, improvement suggestions about them:

1. You can see what status your API is currently is from the top view of your API profile.
On hovering/clicking on present and past phase(s), you'd be able to know when the phase was changed.
You can change the status from that controller
![apiprofile](https://cloud.githubusercontent.com/assets/17976243/20342399/ea8da196-abf2-11e6-9f13-dc0fd859feb8.png)

2. you can filter APIs based on their lifecycle phase from API List and Organization list (if there is developed any)
![apicatalog2](https://cloud.githubusercontent.com/assets/17976243/20342428/0693cf8c-abf3-11e6-8d46-5d82e8c91042.png)
![organizationcatalog3](https://cloud.githubusercontent.com/assets/17976243/20342437/10b01034-abf3-11e6-9692-91615596d7d8.png)

3. this one is regarding to the point arisen by @philippeluickx 
How do you feel about the idea of having a tab in API profile which shows all versions of an API along with their status and status update date.
You can go to the API profiles by clicking into their name (in card or text)
The current API (the profile you are currently at) will be highlightened.
The APIs are linked with arrows showing their ancestry 
![apiprofile4](https://cloud.githubusercontent.com/assets/17976243/20342595/cc563034-abf3-11e6-85c0-282acbcfe3a9.png)

**Comment by TuulaP** [comment]
Oh wow :)  ☕️🍰 

Pic1. Nifty - easy to change own status, so +1 for that.  The Visibility 'Public' altough led my mind to a sidetrack, that could I put 'limited' or private there? Then I could do the initial steps within organization, and publicize the API when stable.  And I hope it is possible to jump directly to 'Stable' so that the workflow doesn't become too strict.

Pic 2. Good. This would help in finding the API with stable condition or those which are in testing mode. How about versions? if a v3 is in Testing and v2 is Stable, so I assume that filters can show different versions of API. Mainly that there is some hint that "btw, there is a stable version available, check that out" kind of info - for experiments you could take the bleeding edge version, but for production the stable one.

Pic 3. For own API management, but for seeing that information from others would be useful. Like in github , repositories with active history/events are such, which one tends to lean on, so the visual history could help in that kind of selection. And also motivate to progress with the API onwards, because the roadmap dates are visible  ;)

**Comment by Nazarah** [comment]
@TuulaP thanks for your feedback. :)

Pic 1: The changing of status is totally upto you. They won't follow a strict workflow so the steps can be changed at any time. I simply kept the usual flow of how an API development usually proceeds.
Public/private visibility of API is an APINF functionality. API owner can control who would be able to see the API in any catalog (private, limited audience, public). So even if your organization is a public one, as long as the API owner doesn't make the visibility public, it won't be available for mass viewing.

pic2: Just for a scenario example, suppose u have 10(!) versions of a single API. :P 
So having a versioning filter might not do the trick.
An idea can be that there is a Name by filtering option.
So, if you select an API name that have multiple versions, all the versions would appear with the latest and stable one being highlighted. How does that idea sounds? :)
Also as mentioned, you can select multiple filtering option for each category (e.g. stable and testing for API phase) so surely you would be able to get your expected filtered result.

pic3: Do you wish to see something similar to history tab mentioning information such as: date od statys change, date of a creating a new version, etc.?

**Comment by TuulaP** [comment]
pic3 . The date of the new version could be useful, just for the cases that if sth breaks up or for own logging. Equally for status change - but somehow so that there is not a multitude of those, so that it is clear to see what is for what.
