### ISSUE TITLE
In API owner's 'Settings' view: 'Connect to Organization' title and its info text not appropriate

### ISSUE THREAD

**Issue by saralavanip** [Digipalvelutehdas/APIKA#186]
# Steps 
1. Visit https://staging.apinf.io   (version 0.37.0)
2. Login as owner 
3. Add API  with proxy  
4. Go to 'Settings'  view  
5. Go to 'Connect to Organization' in 'Details' panel 

# Findings   
- Here the Pre-requisite is to have API connected to an Organization already.  
- The title and its related info. text are not appropriate and its confusing if owner able to connect or disconnect API to an organization.   

# Release
 0.37.0 on staging server 

# Screenshot  
![owner_connect_api](https://cloud.githubusercontent.com/assets/13309358/21451641/3fc9fb18-c909-11e6-9587-5bc9ba260c04.PNG)

**Comment by bajiat** [comment]
@Nazarah Do you have any comments about the report and the info text?

**Comment by saralavanip** [comment]
@bajiat , verified this resolved issue on https://satging.apinf.io ,version 0.38.0 and it is not reproducible. We can close this issue.
