### ISSUE TITLE
Settings view:  'Life cycle status' and 'Connect to organization' options available for APIs not connected to any organization

### ISSUE THREAD

**Issue by saralavanip** [Digipalvelutehdas/APIKA#187]
# Steps 
1. Visit https://staging.apinf.io  (version 0.37.0)
2. Login as owner 
3. Add API  with proxy  
4. Go to 'Settings'  view  

# Findings   
- API life cycle status shown as 'Unknown' 
- In Settings-'Details' panel: 'Life cycle status' and 'Connect to organization' options available for API though not connected to any organization.  

# Release 
 0.37.0 on staging server

# Screenshot  

![api_unknown_label](https://cloud.githubusercontent.com/assets/13309358/21451907/84147c06-c90b-11e6-98d4-10fda5f41019.PNG)

![api_notconnected_lifcycle_panel](https://cloud.githubusercontent.com/assets/13309358/21451900/7878e6a2-c90b-11e6-9107-c247df3dc35b.PNG)

**Comment by bajiat** [comment]
@saralavanip What is your expectation for the following?
> available for API though not connected to any organization.

I'm not sure I understood what was the error reported here.

**Comment by saralavanip** [comment]
@bajiat , we have options 'Life cycle status' and 'Connect to organization' fields in 'Add API' form which are optional. So, if API is added without connecting to any organization, its 'Settings' view has the option to 'disconnect' API from an organization. Is this as expected? or should we have options for both connect and disconnect in settings view?

**Comment by bajiat** [comment]
@saralavanip I think the option available in the Settings is actually Connect API to organization and not Disconnect. The text is slightly misleading. 

The lifecycle status is independent of any connection to an organization. In other words, API can also have a lifecycle status  if it is not connected to an organization.

**Comment by bajiat** [comment]
@Nazarah, can you take a look at the text provided to the user for Connect API to an organization? See the screencapture in the image above. The title is about connecting, while the text talks only about Disconnecting

**Comment by marla-singer** [comment]
@bajiat @Nazarah Connect API to organization will have another UI. These is in process in 201 PR. So help text isn't maybe needed
![joxi_screenshot_1483960239121](https://cloud.githubusercontent.com/assets/20643403/21764696/80a29004-d675-11e6-89c4-c9e45841e44d.png)
![joxi_screenshot_1483960257069](https://cloud.githubusercontent.com/assets/20643403/21764697/8302ea88-d675-11e6-90ca-ac7ca7a990a4.png)

**Comment by bajiat** [comment]
I'll close this issue then.
