### ISSUE TITLE
Submit feedback form not responding

### ISSUE THREAD

**Issue by saralavanip** [Digipalvelutehdas/APIKA#197]
# Steps 
1. Visit https://staging.apinf.io (version 0.37.0)  
2. Login as owner 
3. Click  on 'APIs'   
4. Select an API 
5. Go to 'Feedback' view 
6. Click on 'Send Feedback' button  
7. Fill the feedback form  
8. Click on 'Send' button  

# Expected Result 
Successful in sending feedback  

# Actual Result  
Submit feedback form not responding.

**Comment by snittoor** [comment]
Solved ..

**Comment by saralavanip** [comment]
@bajiat , verified this resolved issue on https://staging.apinf.io version 0.38.0 and it is not reproducible.
