### ISSUE TITLE
Add favicon to branding settings

### ISSUE THREAD

**Issue by Nazarah** [Digipalvelutehdas/APIKA#203]
![image](https://cloud.githubusercontent.com/assets/17976243/21607538/790a2ef2-d1bf-11e6-8195-280c6c8f1c33.png)

**Comment by bajiat** [comment]
There is no method in the UI to change the favicon. Suggestion: add it to the Branding page.

**Comment by bajiat** [comment]
This issue was moved to apinf/platform#2061
