### ISSUE TITLE
Audit translation tokens

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/APIKA#205]
Go through the en. i18n.json file. Make a project-wide search and check that each token is used. If a token is not used/found, remove the token.

For reference, here is how we can get all i18n tokens in use in our software:

```
grep -iRoh '{{_ .*}}' * > all.html.i18n.txt
grep -iRoh 'TAPi18n\.__(.*)' * > all.js.i18n.txt
```
Last time some i18n tags with spaces before the underscore were not found with the search. You can modify the search if you like. Or then double check the missing ones manually.

**Comment by manzapanza** [comment]
@bajiat I'm improving the regex to consider also these extra spaces that could be there. I checked few tokens manually, but now I'm working on a shell script to do everything, what do you think about?
