### ISSUE TITLE
User without permission can see Edit button on organization profile

### ISSUE THREAD

**Issue by marla-singer** [Digipalvelutehdas/APIKA#214]
On the Organization Profile, the Edit button is visible to anonymous users:

![screenshot_20170112_143537](https://cloud.githubusercontent.com/assets/17307/21890048/828251e6-d8d4-11e6-9043-549adfd66321.png)

### Steps
1. As an anonymous user, navigate to an organization
2. Click on Edit button (place is near organization name)
3. Try to edit data

### Found
- Form is opened
- After editing and saving nothing is happened 
- These is error on browser console about "Access denied [403]"

### Expected
- Don't show Edit button to any users, only for limited audience

# Task
Make sure the Edit button only displays for Organization Managers or Admin users. there may already be an `organization.currentUserCanEdit` helper, otherwise we may need to create it.

**Comment by marla-singer** [comment]
@bajiat interested

**Comment by saralavanip** [comment]
@bajiat , verified this resolved issue on https://staging.apinf.io version 0.39.0 and it is not reproducible.
