### ISSUE TITLE
There is no buffer between lifecycle tag and private label in catalog

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/APIKA#219]
# Steps to reproduce
1. Log into https://staging.apinf.io as admin
2. Add a lifecycle label to any API
3. Make the same API private
4. Go to catalog and check the labels in the catalog card for that API
5. Switch to catalog table view and check the two labels for that API

# Expected result
User sees a lifecycle label and private label side by side with some buffer between

# Actual result
Lifecycle label and private label have no buffer between them

# Screenshot
<img width="434" alt="catalog labels no buffer" src="https://cloud.githubusercontent.com/assets/11626388/21845506/9df77d90-d7fb-11e6-8890-ef141f4c8753.png">

**Comment by bajiat** [comment]
Screenshot for Catalog table view: 
<img width="715" alt="labels in catalog table view" src="https://cloud.githubusercontent.com/assets/11626388/21845647/12fe832c-d7fc-11e6-8e92-72297bb585fd.png">

**Comment by bajiat** [comment]
@brylie Can you explain what is the fix?

**Comment by brylie** [comment]
As far as I recall, we just need to add an `&nbsp;` between the labels.

The problem might be related to our internationalization system. When those labels are initially rendered, there is a brief moment where they contain no text. Once the localized text enters the labels, they expand and end up right against one another.

**Comment by bajiat** [comment]
Solved already, closing the issue.
