### ISSUE TITLE
User cannot filter by bookmarks

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/APIKA#221]
1. Visit https://staging.apinf.io  
2. Sign in 
3. Go to Catalog  (default is 'Show all' )
4. Select and bookmark any API(s)
7.  Click on My Bookmarks  

# Expected Result
Displays all bookmarked APIs   

# Actual Result
Shows an empty page   

# Screenshot   

to be added

**Comment by marla-singer** [comment]
@bajiat Done

**Comment by saralavanip** [comment]
@bajiat , verified this resolved issue on https://nightly.apinf.io v 0.40.0 and it is not reproducible.

**Comment by bajiat** [comment]
@saralavanip Thanks for verification!
