### ISSUE TITLE
Anonymous user can see Organization Edit button

### ISSUE THREAD

**Issue by brylie** [Digipalvelutehdas/APIKA#229]
On the Organization Profile, the Edit button is visible to anonymous users:

![screenshot_20170112_143537](https://cloud.githubusercontent.com/assets/17307/21890048/828251e6-d8d4-11e6-9043-549adfd66321.png)

# Task
Make sure the Edit button only displays for Organization Managers or Admin users. there may already be an `organization.currentUserCanEdit` helper, otherwise we may need to create it.

**Comment by marla-singer** [comment]
Dublicate #214
