### ISSUE TITLE
Users list visible to anonymous users

### ISSUE THREAD

**Issue by brylie** [Digipalvelutehdas/APIKA#231]
The users management page can be accessed by anonymous users via URL. This displays all emails and usernames registered on the system.

# Task
Add sufficient security permissions to user related views and publications.

**Comment by bajiat** [comment]
Both of the related PR's are closed. Can we close the issue as well? Or is there remaining work with the publication permissions?

**Comment by saralavanip** [comment]
@bajiat , verified this resolved issue on https://staging.apinf.io version 0.39.0 and it is not reproducible.
