### ISSUE TITLE
Add eslint check to travis build

### ISSUE THREAD

**Issue by mauriciovieira** [Digipalvelutehdas/APIKA#236]
Currently, there is no static code check in the [continuous integration](https://travis-ci.org/Digipalvelutehdas/APIKA). It is desirable to add a eslint check during pull requests because that will help avoiding the introduction of new bugs.

# Definition of done
* [x] Add eslint check to continuous integration (#237)
* [ ] Make eslint to check all directories
  * [x] about (#237)
  * [x] api_catalog (#237)
  * [x] api_keys (#237)
  * [x] apis
    * [x] apis/client (#282)
    * [x] apis/collection (#316)
    * [x] apis/flags (#317)
    * [x] apis/logo (#318)
    * [x] apis/server (#252)
  * [x] apis_authorization (#281)
  * [ ] backlog (#341)
  * [ ] bookmarks (#350)
  * [ ] branding (#351)
  * [ ] core (#352)
  * [ ] dashboard (#353)
  * [x] docker
  * [ ] documentation (#354)
  * [ ] elasticsearch (#355)
  * [ ] feedback (#356)
  * [ ] feedback_votes (#356)
  * [ ] home
  * [ ] metadata
  * [ ] monitoring
  * [x] node_modules
  * [x] organization_apis (#260)
  * [x] organizations (#260)
  * [ ] proxies
  * [ ] proxy_backends
  * [ ] public
  * [ ] ratings
  * [ ] scripts
  * [ ] search
  * [ ] settings
  * [ ] setup
  * [ ] status
  * [ ] users

**Comment by mauriciovieira** [comment]
@bajiat I am working on this. I talked to @brylie Friday and we think it's a good idea.

**Comment by mauriciovieira** [comment]
I am doing this 'locally', and it seems we'll have a long work to do. According to https://travis-ci.org/mauriciovieira/platform/builds/192108795, there are _1656 problems (1358 errors, 298 warnings)_  right after the latest Jan 12th commit (https://github.com/mauriciovieira/platform/commit/0c6b28f7d00ee1eb9328e0341fa829cdd095e827) 

What I propose is to not add all directories in a single step, but one directory at a time, and fix the lints progressively.

**Comment by mauriciovieira** [comment]
And I am pretty sure this step will help us not to introduce new bugs to the code. We already have a https://docs.meteor.com/packages/audit-argument-checks.html to the eslintrc, and it found a lot of non-checked arguments in the code.

**Comment by mauriciovieira** [comment]
I already set up travis ci to run for pull requests and am fixing one issue at at time in https://github.com/Digipalvelutehdas/APIKA/pull/237. Notice the red x for each commit.

**Comment by mauriciovieira** [comment]
@brylie @bajiat I think it's better not to try to lint all directories at once, in this issue. In my opinion, it is better to merge more often, 1 new PR per directory. 

I am finishing the 3 first directories in alphabetical order, and will open an issue for each unlinted directory.

**Comment by mauriciovieira** [comment]
The work is being done in #237

**Comment by mauriciovieira** [comment]
`apis/server` lint is being worked on #252

**Comment by mauriciovieira** [comment]
https://github.com/Digipalvelutehdas/APIKA/pull/252/commits/74328de51413e0bce410206c8c5cd46d68a6cfd4 is a smarter idea to sort this problem out. 

Every time a developer changes a file, they should just remove it from `.eslintignore` and fix the eslint errors.

@brylie what do you think?

**Comment by brylie** [comment]
@mauriciovieira, I linted the Organizations and Organization APIs modules in PR #260.

**Comment by mauriciovieira** [comment]
@brylie @bajiat I left a message on the 3 open pull requests (#246, #255, #266) , telling how the developers can incorporate the current state of these changes into their branches.

**Comment by brylie** [comment]
Great, thanks!

**Comment by bajiat** [comment]
This issue was moved to apinf/platform#2045
