### ISSUE TITLE
Authorize a group to manage APIs of an organization

### ISSUE THREAD

**Issue by tuukka** [Digipalvelutehdas/APIKA#24]
I want to configure APIKA to allow only a given group of users to manage APIs that reside under some domain (digitransit.fi).

# Definition of done
* [ ] An organization manager can add additional managers for an organization through UI. (This uses the same flow as adding API Users)
*  [ ] There is a `managerIds` array field in Organization schema
* [ ] The organization managers have edit rights to the organization information.

# Wireframe

1. In the setting section of Organization profile, there is a separate pane to add managers.
Managers can be added from the existing users in APIKA by their email address.
open question: is there any alternative to add a new manager apart from using APIKA Email? Also can random email address not used in APIKA be used to add a manager?
Texts gives information about what rights managers obtain in an organization.
Already added managers into that organization appears as tags (e.g. https://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/)
![altorganizationprofilesettings3](https://cloud.githubusercontent.com/assets/17976243/21818376/405d98c6-d770-11e6-86fb-a7ac9854341f.png)

2.  To add a manager, a valid email address should be given as input. The new manager gets added after clicking on "Add New Manager".The confirmation of adding a manager can be shown with S-alert (http://s-alert-demo.meteorapp.com/)

![altorganizationprofilesettings4](https://cloud.githubusercontent.com/assets/17976243/21960263/11ab9aca-daed-11e6-8ae4-fd62c4bb828c.png)

**Comment by bajiat** [comment]
Would it be possible to create organizations and organization management support? And APIs would be connected to that organization.

**Comment by philippeluickx** [comment]
+1 on linking it with the organization management. If then whitelabeling (out of scope but on the roadmap) is added, this requirement would be completely covered.

**Comment by bajiat** [comment]
Changed the name of the requirement from: "Authorize a group to manage APIs of a domain" to "Authorize a group to manage APIs of an organization"

**Comment by bajiat** [comment]
@nnn Could you also take this task? Brylie will take a look at the architecture today. Is the estimate correct?

**Comment by Nazarah** [comment]
@bajiat @nnn was working on this and he told that he would ask me later to verify the design. So do I need to make wireframes for this issue from scratch?

**Comment by bajiat** [comment]
@nnn Can you finish this task?

**Comment by bajiat** [comment]
@Nazarah You could experiment with low-fidelity wireframes and then discuss those with @nnn

**Comment by Nazarah** [comment]
@bajiat would the managers added be users in APIKA? that is the new managers can be added using their username/email address used in APIKA? or any random email address (even not registered in APIKA) can be used to add a new manager?

**Comment by Nazarah** [comment]
@bajiat added some sketches of the Organization Settings section with the pane to add new managers to an organization. Please have a look and provide your feedback to it.

**Comment by bajiat** [comment]
@Nazarah Thanks for the wireframes! I have a security concern for this: "On typing string in the input field, all matchin APIKA registered email address would be populated in the dropmenu." I think we can't populate a drop menu. Not all organization managers are admins, which is why we can't disclose email addresses. The managers would simple need to type the entire email address and then add the manager. If the user has not been registered, they would get an error.

**Comment by nnn** [comment]
@bajiat continue working on this task

**Comment by Nazarah** [comment]
@bajiat I modified the wireframes considering your concerns. Now the managers can be added by typing the whole email address and clicking "Add a Manager" button

@nnn Do you have any feedback regarding to the design? I simply kept it like what we now use in API profile settings tab to add limited audience to a private API.
