### ISSUE TITLE
Number of connected APIs is displayed incorrect

### ISSUE THREAD

**Issue by marla-singer** [Digipalvelutehdas/APIKA#240]
Number of connected APIs is displayed incorrect in Organization catalog
Verified on nightly.apinf.io
Screens
![joxi_screenshot_1484564374024](https://cloud.githubusercontent.com/assets/20643403/21980699/572a45f2-dbf5-11e6-88db-40a60bea3959.png)
![joxi_screenshot_1484564386768](https://cloud.githubusercontent.com/assets/20643403/21980700/594e3e2e-dbf5-11e6-885b-01f973de4068.png)

**Comment by saralavanip** [comment]
@baijat, @marla-singer , verified this issue on https://staging.apinf.io version 0.38.0. 
Findings: Number of APIs connected to an organization is not displayed in organization catalog view. 
Screenshots: 
![selection_160](https://cloud.githubusercontent.com/assets/13309358/21983957/5bd765e2-dbfc-11e6-9030-e9ce3913324d.jpg)

![selection_161](https://cloud.githubusercontent.com/assets/13309358/21983930/43ecbab8-dbfc-11e6-8179-eef4a403dbb3.jpg)

**Comment by bajiat** [comment]
@saralavanip It's not in the release yet, that's why you can't see the nr on staging. It will only be part of the next release.

**Comment by saralavanip** [comment]
@bajiat , Ok!

**Comment by bajiat** [comment]
The original error reproduced in nightly.

**Comment by brylie** [comment]
I recommend we add [percolate:publish-counts](https://github.com/percolatestudio/publish-counts#publish-counts) to our project when we need counts of collection documents. It is much more bandwidth efficient, since it only sends the count value as opposed to all of the documents being counted.

**Comment by bajiat** [comment]
Bug reported also in #285.

**Comment by saralavanip** [comment]
@bajiat , verified this resolved issue on https://nightly.apinf.io v 0.40.0 and works as expected.
