### ISSUE TITLE
Unbookmark API in 'My bookmarks' view displays empty page

### ISSUE THREAD

**Issue by saralavanip** [Digipalvelutehdas/APIKA#241]
# Steps 
1. Visit https://staging.apinf.io  (version 0.38.0)
2. Login as owner 
3. Click on 'APIs' 
4. Bookmark any two APIs 
5. Go to filter and click on 'My Bookmarks'
6. Unbookmark any one API by clicking on 'flag' sign

# Findings   
-  Incorrect help text 'Bookmark API' when user bookmarked API already
-  Unbookmark any one API in 'My bookmarks' view displays empty page

# Screenshot  

![selection_163](https://cloud.githubusercontent.com/assets/13309358/21986436/225b3fee-dc08-11e6-9c3d-69fe77bc9bc3.jpg)  

![unbookmark_api](https://cloud.githubusercontent.com/assets/13309358/21986463/39acbfd8-dc08-11e6-82a5-32d55b83a0a4.png)  

![selection_164](https://cloud.githubusercontent.com/assets/13309358/21986540/8395d756-dc08-11e6-94e4-c21f79b7d78a.jpg)

**Comment by bajiat** [comment]
@saralavanip This should be resolved. Please verify this with release 0.39.0, when it has been deployed to staging. Closing the issue.

**Comment by saralavanip** [comment]
@bajiat , verified this resolved issue on https://staging.apinf.io version 0.39.0 and it is not reproducible.
