### ISSUE TITLE
Possibility for admin or manager to 'Delete' organization

### ISSUE THREAD

**Issue by saralavanip** [Digipalvelutehdas/APIKA#248]
# Steps 
1. Visit https://staging.apinf.io (version 0.38.0) 
2. Login as admin 
3. Go to 'Organizations'  
4. Add Organization
5. Click on 'Organization' added above 

# Findings  
-   Currently admin or manager can edit the details of the organization but cannot delete the organization.

**Comment by marla-singer** [comment]
@bajiat Suggestion for UI the same as API profile has
![joxi_screenshot_1485173294951](https://cloud.githubusercontent.com/assets/20643403/22203378/d9090b66-e17d-11e6-9692-0e48ef5429a0.png)

**Comment by bajiat** [comment]
@marla-singer I'm ok with this UI.

@Nazarah Any comments?

**Comment by Nazarah** [comment]
@marla-singer @bajiat I am ok with the UI.
