### ISSUE TITLE
'Search' icon clickable while another search field available with its results

### ISSUE THREAD

**Issue by saralavanip** [Digipalvelutehdas/APIKA#254]
# Steps  
1. Visit https://staging.apinf.io  (version 0.38.0) 
2. Go to search field 
3. Enter a search word (eg. test) and click on 'Search' button 
4. Go to topbar and click on 'search' icon (magnifying glass)

# Findings 
-  The first search (step 3) displays search results with a search field 
-  While clicking on search icon on topbar opens up another search field 

# Expected Result 
-  Search icon on topbar should not be clickable while there is already one available along with search results 

# Screenshot   

![multiple_serach_fields](https://cloud.githubusercontent.com/assets/13309358/22063250/75d7b7c2-dd86-11e6-9c70-22b6b846ee14.PNG)

**Comment by bajiat** [comment]
Suggestion from @brylie If the current page/route is Search, do not display the top Search field

**Comment by bajiat** [comment]
@manzapanza Would you like to take this task?

**Comment by saralavanip** [comment]
@bajiat , verified this resolved issue on https://nightly.apinf.io v 0.40.0 and it is not reproducible.
