### ISSUE TITLE
Search with keyword in 'Suomi' view displays search results in 'English' view

### ISSUE THREAD

**Issue by saralavanip** [Digipalvelutehdas/APIKA#256]
# Steps 
1. Visit https://staging.apinf.io (version 0.38.0)   
2. Go to languages on topbar and click on 'Suomi' 
3. Go to search field and enter keyword (eg. test) 
4. Click on 'Hae' 

# Expected Result 
Displays search results in 'Suomi' view 

# Actual Result  
Displays search results in 'English' view 

# Screenshot 
![suomi_view_search](https://cloud.githubusercontent.com/assets/13309358/22063682/bee02fc4-dd88-11e6-9e5a-3c642dd05391.PNG)
![suomi_view_search_results_english](https://cloud.githubusercontent.com/assets/13309358/22063688/c3fcb8d8-dd88-11e6-908d-9b9971b7c9e0.PNG)

**Comment by marla-singer** [comment]
@bajiat Researched this issue. The search page has Finnish translation. Can be related to #258

**Comment by saralavanip** [comment]
@bajiat , verified this resolved issue on https://nightly.apinf.io v 0.40.0 and it is not reproducible.
