### ISSUE TITLE
Suomi view:  Input field title text in 'Add API' form are untranslated

### ISSUE THREAD

**Issue by saralavanip** [Digipalvelutehdas/APIKA#257]
# Steps 
1. Visit https://staging.apinf.io (version 0.38.0) 
2. Change language by clicking on 'Suomi' 
3. Sign up 
4. Click on 'Add API'  
 
# Findings  
Suomi view: Input field titles text in 'Add API' form are in English language 

# Screenshot  
![add_api_form_suomi_view](https://cloud.githubusercontent.com/assets/13309358/22065789/725d55b4-dd92-11e6-8372-45090392cc36.PNG)

**Comment by bajiat** [comment]
First step: Check that the texts are included in i18n file

**Comment by saralavanip** [comment]
@bajiat , verified this resolved issue on https://nightly.apinf.io v 0.40.0 and it is not reproducible.
