### ISSUE TITLE
Refresh page in 'Suomi' view changes to 'English' view

### ISSUE THREAD

**Issue by saralavanip** [Digipalvelutehdas/APIKA#258]
# Steps
1. Visit https://staging.apinf.io (version 0.38.0) 
2. Change the language to 'Suomi'  
3. Click on 'Rajapinnat'  (APIs)  
4. Refresh/reload page  

# Findings
Refresh page in Suomi view changes to 'English' view

**Comment by philippeluickx** [comment]
As far as I know, this can only be solved by having a parameter in the URL. Either query parameter (?language=fi) or part of the url (apinf.io/fi/apis).

**Comment by marla-singer** [comment]
As for me, part of URL looks better.

**Comment by saralavanip** [comment]
@bajiat , verified this resolved issue on https://nightly.apinf.io v 0.40.0 and works as expected.
