### ISSUE TITLE
Refresh in dashoard page: filter parameters persist, but API list gets refreshed

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/APIKA#265]
# Steps to reproduce
1. Log into staging.apinf.io as admin (= can see any API on dashboard)
2. Select an API from the list
3. Select a filter, e.g. Hour
4. Refresh the page

# Expected result
Any filtering persists on dashboard

# Actual result
URL filters persist: data on charts is for the previously selected API and for the selected time filter. However, the API select list gets refreshed and is showing the name for the default API (first one on the list).

# Screenshots

API and timeframe selected:
<img width="887" alt="dashboard_step1" src="https://cloud.githubusercontent.com/assets/11626388/22111833/7fe88fd2-de69-11e6-9491-98a5afc760e8.png">

After refresh API list shows default API, but the data  is for the originally selected API based on URL parameters:
<img width="826" alt="dashboard_step2" src="https://cloud.githubusercontent.com/assets/11626388/22111879/a78c6540-de69-11e6-9326-71bde0ec4435.png">

**Comment by bajiat** [comment]
@brylie You had an idea on how to get the API id parameter. Can you explain as a comment to give @snittoor a starting point?

**Comment by bajiat** [comment]
@snittoor Please note that #336 is related

**Comment by brylie** [comment]
@marla-singer can you pair program with @snittoor on this task?

**Comment by marla-singer** [comment]
@brylie Sorry, don't have enough time for that

**Comment by brylie** [comment]
OK, she just needs to pull a URL parameter into the select menu, so the correct item is selected.

**Comment by brylie** [comment]
I think the solution would look like this:

```
// in /dashboard/client/filtering/api_select/api_select.js
Template.apiSelectPicker.onRendered(function () {
  
  // Get Proxy Backend ID parameter from URL,
  const proxyBackendId = FlowRouter.getQueryParam('backend');

  if (proxyBackendId) {
    // Update the select menu to match the Proxy Backend ID
    $('#proxy-backend-select').val(proxyBackendId);
  }
});
```
