### ISSUE TITLE
OrganizationApis module is not updated when user deletes API

### ISSUE THREAD

**Issue by marla-singer** [Digipalvelutehdas/APIKA#279]
OrganizationApis module is not updated when user deletes API

### Step

1. Create an Organization and an API, navigate to Organization
2. Pay attention that Organization profile doesn't have connected API and doesn't have the title "**APIs**" as expected. There are empty area in blue frame on screenshot (as expected)
![joxi_screenshot_1485186270442 1](https://cloud.githubusercontent.com/assets/20643403/22210938/7a7888b4-e19c-11e6-9ac5-2c6ac1374927.png)
3. Connect a created API to created organization. 
4. The APIs title has appeared on Organization profile as expected
![joxi_screenshot_1485186270442](https://cloud.githubusercontent.com/assets/20643403/22211046/de1d0f3e-e19c-11e6-8244-32437ccc599b.png)
5. Go to API page and delete it
6. Navigate to Organization

### Found
- Title **APIs (0 apis)** 
![joxi_screenshot_1485186852320](https://cloud.githubusercontent.com/assets/20643403/22211202/5e36a3c4-e19d-11e6-8dee-3972cea601e9.png)
### Expected
- Empty area as before connection
### Reasons
- It happens because OrganizationApis collection has record about deleted API. You can see it on screenshot

![2017-01-23 18 55 45](https://cloud.githubusercontent.com/assets/20643403/22211327/b8c86ef8-e19d-11e6-91cd-4326fb5275ab.png)

**Comment by saralavanip** [comment]
@bajiat , verified this resolved issue on https://nightly.apinf.io v 0.40.0 and it is not reproducible.
