### ISSUE TITLE
Bookmark API, info text remains displayed in Organization profile

### ISSUE THREAD

**Issue by saralavanip** [Digipalvelutehdas/APIKA#283]
# Steps 
1. Visit https://staging.apinf.io (version 0.39.0)   
2. Login as admin   
3. Add Organization 
4. Go to above added organization profile 
6. Click on 'Connect API to organization'
7. Select any API from drop down menu  
8. Click on 'Connect' button  
9. Bookmark the above API added clicking on 'flag' icon  

# Findings 
-  The info text for bookmark or unboomark API remains displayed. 
-  Refresh page doesn't display bookmark info text though.    

# Operating system 
Windows 10  

# Browser 
Internet Explorer 11

# Screenshot  
![bookmark_api_info_text](https://cloud.githubusercontent.com/assets/13309358/22240140/5e28c6a2-e222-11e6-96ac-dc01770a8494.PNG)

![unbookmark_info_remains](https://cloud.githubusercontent.com/assets/13309358/22240061/fc7ad896-e221-11e6-8363-dc4b5fff2912.PNG)  

![bookmark_api_info_text_api_cards](https://cloud.githubusercontent.com/assets/13309358/22240051/ef71b714-e221-11e6-984b-83773b2d07a9.PNG)

**Comment by bajiat** [comment]
I don't see how step 8 is relevant to do while you are connecting an API and the modal dialog is being displayed.

**Comment by bajiat** [comment]
This issue was moved to apinf/platform#2055
