### ISSUE TITLE
Filter APIs by Lifecycle status, 'Clear all' button not available in results view

### ISSUE THREAD

**Issue by saralavanip** [Digipalvelutehdas/APIKA#284]
# Steps  
1. Visit https://staging.apinf.io (version 0.39.0)   
2. Login as admin/owner   
3. Add APIs  with Lifecycle status (eg. Testing)
3. Click on 'APIs' 
4. Bookmark any APIs  
5. Filter APIs by Lifecycle status clicking on 'filter' icon 
5. Select an option (eg. 'Testing') from drop down menu

# Findings  
-  Filter APIs by Lifecycle status is successful and they are listed as expected. 
-  'Clear all' button not available in this view 
-  If user clicks on  'My APIs' or My Bookmarks without clearing the above results ,it displays empty page. 

# Screenshot    
![no_clearall_button_api_filter_results_view](https://cloud.githubusercontent.com/assets/13309358/22243631/d9fcd242-e230-11e6-87c4-2b6c7b95457b.PNG)

**Comment by bajiat** [comment]
> If user clicks on 'My APIs' or My Bookmarks without clearing the above results ,it displays empty page.

This is not a bug. The filter should persist if it has not been cleared. You can find the Clear button by pressing the filter button again.

However, this is not consistent with the Organization page that has a Clear all button.

I would suggest removing the text about filtering and the Clear all button from Organization profile to keep the pages consistent. Any comments from @Nazarah or @apinf/developers ?

**Comment by bajiat** [comment]
Also, set the filter button to active on both API Catalog page and on Organization page.

**Comment by bajiat** [comment]
This issue was moved to apinf/platform#2037
