### ISSUE TITLE
Filter by 'My organizations' shows all organizations

### ISSUE THREAD

**Issue by saralavanip** [Digipalvelutehdas/APIKA#286]
# Steps 
1. Visit https://staging.apinf.io  (version 0.39.0)   
2. Login as admin   
3. Add Organizations
4. Click on 'Organizations' in navbar 
5. Go to filter and click on 'My organizations' bar 

# Expected Result 
It must show only my organizations 

# Actual Result
- Shows all organizations. 
- From this view :  if user clicks on 'Organizations' in navbar it shows empty page  
- This issue is also reproducible on https://nightly.apinf.io v 0.39.0   

# Screenshot     

![nightly_filter_myorgs_shows_all_organizations](https://cloud.githubusercontent.com/assets/13309358/22246517/eec264aa-e23d-11e6-91db-1ebb3ea13ffc.PNG)

![staging_org_catalog_empty_page](https://cloud.githubusercontent.com/assets/13309358/22246437/afe38ac0-e23d-11e6-9458-f28ef0d96d35.PNG)   

![nightly_org_catalog_empty_page](https://cloud.githubusercontent.com/assets/13309358/22246452/bce2e45a-e23d-11e6-831b-e2312613c20c.PNG)

**Comment by marla-singer** [comment]
@bajiat I will look at it

**Comment by marla-singer** [comment]
Closing this issue via PR #292

**Comment by marla-singer** [comment]
Closing this issue via PR #292
