### ISSUE TITLE
Title and page title should be the same

### ISSUE THREAD

**Issue by kyyberi** [Digipalvelutehdas/APIKA#291]
Perhaps it would make more sense to use word "Rajapintaluettelo" (now "Rajapinnat") in the top menu as well since the title in the page is "Rajapintaluettelo". Or visa versa: use Rajapinnat in the menu and in page title as well. 
![kuvakaappaus 2017-01-25 07-36-15](https://cloud.githubusercontent.com/assets/1927158/22279107/313e57d8-e2d1-11e6-9afe-10a43fb119b1.png)

**Comment by kyyberi** [comment]
Same formatting applies to Organizations view as well.

**Comment by bajiat** [comment]
This issue was moved to apinf/platform#2054
