### ISSUE TITLE
Fix links in About

### ISSUE THREAD

**Issue by nnn** [Digipalvelutehdas/APIKA#294]
Some links are incorrect on About modal.
Specifically: 
[https://apinf.org](https://apinf.org) should be [http://apinf.org](http://apinf.org)
[https://apinf.org/docs](https://apinf.org/docs) should be [http://apinf.org/docs](http://apinf.org/docs)
We can check if it possible to have these links with https, but for now we need to make sure users are getting to working website.

**Comment by saralavanip** [comment]
@bajiat , verified this resolved issue on https://nightly.apinf.io v 0.40.0 and works as expected.
