### ISSUE TITLE
Email verification link of a deleted account enables automatic login

### ISSUE THREAD

**Issue by saralavanip** [Digipalvelutehdas/APIKA#297]
# Steps  
1. Visit https://staging.apinf.io  (version 0.39.0) 
2. Create account 1 (eg. with email address: test1@test.com)
3. Open email and click on account 1 verification link 
4. Visit https://staging.apinf.io
5. Login as admin and delete the above added account  
6. Logout 
7. Create another account 2 (eg. with email address: test2@test.com) 
8. Open email and click on account 2 verification link 
9. Repeat step 3  

# Findings  
- Click on email verification link of a deleted account, enables automatic login to the latest active account. 
- Displays error message 'Verify email link Expired'   

# Screenshot  
![screenshot 90](https://cloud.githubusercontent.com/assets/13309358/22300349/d961d828-e32f-11e6-92e0-81718fc0fc62.png)

**Comment by nnn** [comment]
Interested.

**Comment by bajiat** [comment]
This issue was moved to apinf/platform#2031
