### ISSUE TITLE
 'Contact Us' link not working

### ISSUE THREAD

**Issue by saralavanip** [Digipalvelutehdas/APIKA#298]
# Steps 
1. Visit https://staging.apinf.io (version 0.39.0) 
2. Scroll down and go to 'Reach out to developers'
3. Click on link 'Contact Us' 
 
# Expected Result 
Click on 'Contact Us' must redirect to contact form  

# Actual Result 
It doesn't redirect to contact form

**Comment by nnn** [comment]
@saralavanip, please confirm.

**Comment by marla-singer** [comment]
@nnn Your PR will be available on staging after release. Changes will be available on nightly  tomorrow

**Comment by nnn** [comment]
@marla-singer, aware of this, just a reminder.

**Comment by saralavanip** [comment]
@nnn , @bajiat ,  verified this resolved issue on https://staging.apinf.io version 0.40.0 and it works as expected in Firefox (v 51.0.1) and Chrome(v 56.0.2924.87) browsers. 

Findings in IE 11 browser: Click on 'Contact Us' not working 

Screenshot: 
![screenshot 95](https://cloud.githubusercontent.com/assets/13309358/22730470/c6907630-edef-11e6-915d-03fbd40004ab.png)
