### ISSUE TITLE
Text field titles in 'Contact and Registration' forms are untranslated in Suomi view

### ISSUE THREAD

**Issue by saralavanip** [Digipalvelutehdas/APIKA#299]
# Steps 
1. Visit https://staging.apinf.io (version 0.39.0) 
2. Change language by clicking on 'Suomi'   
3. Go to 'Getting started' and click on  'Register' ('Rekisteroidy')  
4. Scroll down and go to 'Contact Us' 

# Expected Result 
All the text field titles in Contact and Registration forms must be in Suomi language   

# Actual Result  
Text filed titles are untranslated in Suomi view   

# Screenshot  

![contact_form_text_field_titles_suomi_view](https://cloud.githubusercontent.com/assets/13309358/22323183/baf72ed6-e3a9-11e6-9d7a-eb49d8b74cdd.PNG)

**Comment by marla-singer** [comment]
@baijat Verified it on nightly, it is reproduced

**Comment by marla-singer** [comment]
@bajiat The form has the translation. But it doesn't work as expected, an fixing it.

**Comment by saralavanip** [comment]
@bajiat , verified this resolved issue in https://staging.apinf.io version 0.40.0 

Findings:  
-  Text field titles in 'Contact Us' form are as expected in Suomi view  (screenshot 1) 
- Registration form is untranslated in Suomi view (eg. Page title , text field titles) (screenshot 2)  

Screenshot 1: 
![suomi_contact_us_form](https://cloud.githubusercontent.com/assets/13309358/22730976/c60920d4-edf1-11e6-8faa-d4d33dfc5d23.PNG)  

Screenshot 2:  
![suomi_sign_up_page](https://cloud.githubusercontent.com/assets/13309358/22730995/d1e02722-edf1-11e6-8bc0-0263795f6433.PNG)
