### ISSUE TITLE
Anonymous users can view 'Private' APIs listed in 'Organization catalog'

### ISSUE THREAD

**Issue by saralavanip** [Digipalvelutehdas/APIKA#301]
# Steps  
1. Visit https://staging.apinf.io (version 0.39.0)   
2. Login as admin 
3. Add API 
4. Go to 'My APIs' and click on above API added 
5. Click on Settings 
6. Change the visibility of API from to 'Private'  
7. Add Organization 
8. Connect the API to above Organization  
9. Logout 
10. Again visit https://staging.apinf.io  
11. Navigate to 'Organizations catalog' and select the above organization  

# Expected Result   
-  Private APIs should not be available  in organization catalog for anonymous users. 
-  Only admin or the owner of that particular private labeled API can view in organization  catalog  

# Actual Result  
-  Private APIs  available  in organization catalog for anonymous users. 
-  Select this private API , displays error: 403 'You don't have permissions to view this page' 
- Click on 'Return to previous page' is unresponsive   

# Screenshot   
![anonymous_users_view_private_apis_org_catalog1](https://cloud.githubusercontent.com/assets/13309358/22325046/1178e654-e3b5-11e6-90e9-9b17e86f95a8.PNG)

![anonymous_users_view_private_apis_org_catalog](https://cloud.githubusercontent.com/assets/13309358/22325002/dbe57b9c-e3b4-11e6-8538-f467df8305ae.PNG)

**Comment by marla-singer** [comment]
@bajiat I willlook at it

**Comment by bajiat** [comment]
@marla-singer Thanks for assigning yourself!

**Comment by marla-singer** [comment]
@bajiat Need a clarification about how can see private API in organization profile?
1. Administrator
2. API owner
3. Organization manager (?)

**Comment by saralavanip** [comment]
@bajiat , verified this resolved issue on https://staging.apinf.io v 0.40.0 and it is not reproducible.
