### ISSUE TITLE
On connecting an API in an organization,  related card in the organization catalog doesn't change the number of APIs

### ISSUE THREAD

**Issue by Nazarah** [Digipalvelutehdas/APIKA#305]
# Reproduction steps.

1. Go to https://nightly.apinf.io 
2. Sign in as an admin and  Click "Organizations"
3. click on any organization.
4. in Organization profile, click "Connect API to Organization".
5. Select an API and click Connect. (Connected API appears in organization profile)

![image](https://cloud.githubusercontent.com/assets/17976243/22340392/03a001de-e3f6-11e6-8983-d92c52bc00f8.png)

6. Return to organization catalog.

# Result

In organization catalog, no. of connected API doesn't change in Organization card.
It always remains as 0.

![image](https://cloud.githubusercontent.com/assets/17976243/22340420/164333ba-e3f6-11e6-9c9c-38d935a08247.png)

# Environment

* OS: Windows 8
* Browser: Chrome

**Comment by marla-singer** [comment]
@Nazarah Duplicate of #240

**Comment by Nazarah** [comment]
thanks for notifying @marla-singer , should I close the issue then?

**Comment by marla-singer** [comment]
@Nazarah Yep

**Comment by Nazarah** [comment]
Closing the issue for duplicity #240
