### ISSUE TITLE
For Filtering APIs in Organization profile and API catalog, users should be able to choose more than one lifecycle status

### ISSUE THREAD

**Issue by Nazarah** [Digipalvelutehdas/APIKA#306]
# Usability Issue

Right now, the filtering option has the lifecycle statuses of API as dropmenu. User is able to select only one status type from there. User might wish to filter APIs connected to an organization / API catalog with more than one lifecycle status.

![image](https://cloud.githubusercontent.com/assets/17976243/22340737/22aa1460-e3f7-11e6-826e-097f69167183.png)

# Suggestion

Make the drop menu option selection such that user is able to select more than one life cycle status.
Checked lifecycle statues can appear on the filter pane as tags (e.g. using bootstrap tags)

![altorganizationprofileapifilter2](https://cloud.githubusercontent.com/assets/17976243/22340896/a3c996f6-e3f7-11e6-9368-1b8879b58023.png)

**Comment by bajiat** [comment]
This issue was moved to apinf/platform#2053
