### ISSUE TITLE
In API profile, lifecycle tag and private tag have no space in between

### ISSUE THREAD

**Issue by Nazarah** [Digipalvelutehdas/APIKA#308]
# Usability Issue

Right now, on making an API private, the API profile has lifecycle and private tag placed beside each other with no space. This decreases UI aesthetics and makes confusion in realizing visibility and lifecycle information. Also, if there would be  lifecycle status changing information, it won't be placed adjacent to the status tag.

# Suggestion.

Place the private tag below the lifecycle status, so that they differentiate the information they represent. Also this would make it possible to display lifecycle changing information (if implemented).

![lifecycleapiprofile3private](https://cloud.githubusercontent.com/assets/17976243/22341936/729fdb18-e3fb-11e6-9615-90628c581117.png)

**Comment by marla-singer** [comment]
@Nazarah I'm working on space between labels. Place the private tag below the lifecycle status is a good idea but it can be case that username is long but API name is short 
![joxi_screenshot_1485504676051](https://cloud.githubusercontent.com/assets/20643403/22364274/57334d70-e481-11e6-9d5f-078c2b56315c.png)

**Comment by bajiat** [comment]
@marla-singer @Nazarah I prefer just adding space between the labels like we did on the card view, instead of using two rows to show labels.

**Comment by Nazarah** [comment]
@bajiat we can continue with the solution for "adding space" between two labels. However, we might need to do rework if we decide to show recent status change history in future. For the time being, we can go with the quick solution.
@marla-singer should I assign you in this issue? then you can close it once you have fixed the problem.
