### ISSUE TITLE
Incorrect total number of organizations in front page

### ISSUE THREAD

**Issue by marla-singer** [Digipalvelutehdas/APIKA#311]
Verified on nightly.apinf.io
Place: front page

### Found
![joxi_screenshot_1485502405162](https://cloud.githubusercontent.com/assets/20643403/22363560/489919ac-e47c-11e6-8253-bdb2628542d3.png)
### Actually
We have 5 organizations
![joxi_screenshot_1485502418609](https://cloud.githubusercontent.com/assets/20643403/22363569/4fdea006-e47c-11e6-8c24-d91b6034d696.png)

### Reason 
Incorrect import of Organizations collection

**Comment by saralavanip** [comment]
@bajiat , verified this resolved issue on nightly v 0.40.0 and it works as expected.
