### ISSUE TITLE
Align the lifecycle status tag in API profile with the API name

### ISSUE THREAD

**Issue by Nazarah** [Digipalvelutehdas/APIKA#319]
# UI Issue
Right now the lifecycle status doesn't appear aligned with the API name. This is not good aesthetics. 

![image](https://cloud.githubusercontent.com/assets/17976243/22416596/33777182-e6d8-11e6-916e-0efb0e435a2b.png)

# Solution
1. place the tag s.t. API name and the tag are in the same line.
OR
2. if the tag is smaller in height than API name font size, then place the tag mid-aligned with the API name font size.

**Comment by bajiat** [comment]
This issue was moved to apinf/platform#2049
