### ISSUE TITLE
Get access to APIKA VM

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/APIKA#32]
Make sure the APInf team making APIKA deployments has access to APIKA server(s). Access information needs to be stored securely, so that any backup person can also handle deployments.

**Comment by kyyberi** [comment]
Ville Jyrkkä should have SSH access

**Comment by jykae** [comment]
@bajiat Have access for current apikafront & umbrella. Investigating access for Pouta to create new VM for migration.

**Comment by jykae** [comment]
@shaliko & me have now access for migration server. Closing
