### ISSUE TITLE
In "About" section for APIKA, information about APInf is displayed.

### ISSUE THREAD

**Issue by Nazarah** [Digipalvelutehdas/APIKA#321]
# Steps to reproduce
1. Go to https://apika.digipalvelutehdas.fi
2. Click About on topbar.

#Result:
Information about APInf instead of APIKA is displayed.

![image](https://cloud.githubusercontent.com/assets/17976243/22419932/6a29a9b0-e6e8-11e6-9bed-1283aa9bb283.png)

# Expected Result
platform specific field names and values should appear in the About Dialog.

**Comment by Nazarah** [comment]
When fixing the bug, please make sure Finnish translations are updated as well.

**Comment by bajiat** [comment]
In my opinion, it should be Apinf. The SW version is Apinf release 0.39 and so on. But I'll get a second opinion on this.

**Comment by Nazarah** [comment]
We can keep the information about Apinf. What we can do here is to give a disclaimer text saying APIKA is built using Apinf or something similar like this.

**Comment by brylie** [comment]
I like @Nazarah's suggestion, but would add that the text should be generic, rather than use the platform branding (`title`). The reason for this is the `about` page is just a static HTML file, so adding any text from the `Branding` collection would add unnecessary complexity.

**Comment by Nazarah** [comment]
I am fine with the solution.
