### ISSUE TITLE
Deleting an API doesn't remove it from proxy. So on adding the same API in APIKA shows previously made requests in Dashboard

### ISSUE THREAD

**Issue by Nazarah** [Digipalvelutehdas/APIKA#324]
# Reproduction Steps:

1. Sign in to https://apika.digipalvelutehdas.fi/
2. Add an API with proper URL
3. Go to proxy tab in API profile and provide Proxy Base Path and API Base path.
4. Make a call to the API.
5. Go to Dashboard and select the added API from the dropmenu. Remember the no. of request.
6. Go to API profile and delete the API.
7. After confirming the deletion, add the same API. (includng the proxy base path and API base path)
8. go to Dashboard and select the API from dropmenu.

# Result:
Dashboard shows the number of requests made before the API was deleted and readded.

![apiproxydeletion](https://cloud.githubusercontent.com/assets/17976243/22425275/fdc3c5a6-e702-11e6-99ae-a27b933976fa.gif)

# Expected Result
API details should also be deleted from proxy on deleting an API.
So that when the same API is added again, Dashboard should show fresh history (of 0 or requests made after added, etc.) than the previous history of requests.

# Environment
Chrome, Windows 8

**Comment by bajiat** [comment]
This should be verified in staging and nightly, not on apika server.

**Comment by bajiat** [comment]
@marla-singer Would you be interested in this task?

**Comment by marla-singer** [comment]
@bajiat Yes, I'd . Estimated

**Comment by bajiat** [comment]
This issue was moved to apinf/platform#2032
