### ISSUE TITLE
API documentation editor not working

### ISSUE THREAD

**Issue by saralavanip** [Digipalvelutehdas/APIKA#325]
# Steps  
1. Visit https://staging.apinf.io  
2. Login as admin 
3. Navigate to 'Settings' 
4. Enable 'API documentation editor'  
5. Enter details of 'Host'  (eg. http://editor.swagger.io/) 
6. Click on 'Save' button 
7. Add API 
8. Go to 'My APIs' and select above added API 
9. Go to 'Documentation' and click on 'Manage' button 
10. Click on 'Open API documentation editor'  

# Finding
Click on 'Open API documentation editor' displays empty page     

# Screenshots  
![manage_api_doc_editor](https://cloud.githubusercontent.com/assets/13309358/22428129/9075df64-e70e-11e6-8bf0-69890894c302.PNG)

![click_api_doc_editor_empty_page](https://cloud.githubusercontent.com/assets/13309358/22428006/0829c788-e70e-11e6-96ef-5506e3e01dd0.PNG)

**Comment by ccsr** [comment]
This is a DevOps issue and is fixed now. It can be accessed at https://editor.apinf.io/
Thanks to @shaliko for fixing this.

**Comment by saralavanip** [comment]
@bajiat , based on above comment, verified this issue on https://staging.apinf.io v 0.40.0 and it is reproducible. 
Screenshot: 
![admin_settings_doc_editor_details](https://cloud.githubusercontent.com/assets/13309358/22733643/56f4e9c6-edfb-11e6-9ff0-ff18923cc5be.PNG)    
![doc_editor_empty_page](https://cloud.githubusercontent.com/assets/13309358/22733746/c7fcb55e-edfb-11e6-8555-58049397aab3.PNG)
