### ISSUE TITLE
APIKA: In Branding page, Colors pane texts don't have Finnish translations

### ISSUE THREAD

**Issue by Nazarah** [Digipalvelutehdas/APIKA#326]
![image](https://cloud.githubusercontent.com/assets/17976243/22455433/31860e20-e795-11e6-971b-d92543c51870.png)

**Comment by marla-singer** [comment]
@bajiat Verified on night, isn't reproduced. Can be closed
![joxi_screenshot_1485936002270 1](https://cloud.githubusercontent.com/assets/20643403/22499168/2b32a932-e86e-11e6-9027-d8e62d2b4d6f.png)

**Comment by Nazarah** [comment]
As the issue was found in APIKA, I suggest to keep the issue till the latest deployment is made. When I verify the issue in APIKA that it has been resolved, I can close the issue myself.

**Comment by bajiat** [comment]
Duplicate.

@Nazarah, I will close the issue now. If it is resolved in nightly, it gets to the next release.
