### ISSUE TITLE
APIKA: In Branding page, Social Media pane texts don't have Finnish translations

### ISSUE THREAD

**Issue by Nazarah** [Digipalvelutehdas/APIKA#327]
![image](https://cloud.githubusercontent.com/assets/17976243/22455565/08cc4ade-e796-11e6-8798-bf29cf6d83a9.png)

**Comment by marla-singer** [comment]
@baijat Verified it on nightly. it's reproduced as part. Only first option (Select one) doesn't have translate. I'm researching the problem

**Comment by bajiat** [comment]
This issue was moved to apinf/platform#2048
