### ISSUE TITLE
APIKA: In Settings page, the following pane texts need Finnish translations

### ISSUE THREAD

**Issue by Nazarah** [Digipalvelutehdas/APIKA#328]
1. Adding API
![image](https://cloud.githubusercontent.com/assets/17976243/22455710/0c4cc3cc-e797-11e6-94f1-8f00f21e66d1.png)

2. Sähköposti
![image](https://cloud.githubusercontent.com/assets/17976243/22455764/55362eb6-e797-11e6-8119-6c8546c5eade.png)

3. GitHub
![image](https://cloud.githubusercontent.com/assets/17976243/22455793/75aa91fa-e797-11e6-827b-4354af8eaf0c.png)

**Comment by marla-singer** [comment]
@baijat Verified it on nightly. it's reproduced. I'm researching the problem

**Comment by marla-singer** [comment]
@bajiat Check it again. **Client ID** and **Secret** are specified so in Finnish file. See below:
https://github.com/Digipalvelutehdas/APIKA/blob/develop/core/lib/i18n/fi.i18n.json#L659-L663

**Comment by marla-singer** [comment]
What about "Sähköposti" form - it has Finnish translate, but it doesn't work

**Comment by marla-singer** [comment]
Adding APIs has translate (screen)
![joxi_screenshot_1485961364365](https://cloud.githubusercontent.com/assets/20643403/22512018/a9064aa0-e8a8-11e6-81a2-e00647239ce8.png)

"Only platform administrators are allowed to add new APIs" has translate as well, but it doesn't work
