### ISSUE TITLE
APIKA: In Account page, Account Details pane texts need Finnish traslations

### ISSUE THREAD

**Issue by Nazarah** [Digipalvelutehdas/APIKA#329]
![image](https://cloud.githubusercontent.com/assets/17976243/22455952/2dd9d7e0-e798-11e6-8ee4-0b6b48d4cdff.png)

**Comment by marla-singer** [comment]
@bajiat Verified it on nightly. it's reproduced. I'm researching the problem

**Comment by marla-singer** [comment]
@bajiat This form doesn't have tags. The labels was hard coded. Fixed it. It will need another translation round
