### ISSUE TITLE
APIKA: Save button in Add Organization dialogue needs Finnish translation

### ISSUE THREAD

**Issue by Nazarah** [Digipalvelutehdas/APIKA#332]
Language has been kept as Suomi

![image](https://cloud.githubusercontent.com/assets/17976243/22461867/ba41812c-e7b3-11e6-91a9-15604f873a0a.png)

**Comment by marla-singer** [comment]
@bajiat Verified on nightly, isn't reproduced. Can close it
![joxi_screenshot_1485935828154](https://cloud.githubusercontent.com/assets/20643403/22499015/45a60602-e86d-11e6-905e-84ccdd0e90cb.png)

**Comment by Nazarah** [comment]
As the issue was found in APIKA, I suggest to keep the issue till the latest deployment is made. When I verify the issue in APIKA that it has been resolved, I can close the issue myself.

**Comment by marla-singer** [comment]
@Nazarah If it was resolved in nightly then the changes will be available in APIKA as well. APIKA isn't updated so often as Nightly but have the same code
