### ISSUE TITLE
"Private" label doesn't have Finnish translate

### ISSUE THREAD

**Issue by marla-singer** [Digipalvelutehdas/APIKA#334]
Screenshot
![joxi_screenshot_1485872873825](https://cloud.githubusercontent.com/assets/20643403/22462952/68e293d6-e7a7-11e6-8b01-7fed6a22b726.png)
![joxi_screenshot_1485872873825 1](https://cloud.githubusercontent.com/assets/20643403/22462956/6b5cb9b6-e7a7-11e6-9ea9-351909dfa851.png)

**Comment by saralavanip** [comment]
@bajiat , verified this resolved issue on https://nightly.apinf.io v 0.40.0 and it is not reproducible.
