### ISSUE TITLE
In Suomi setting, Filtering option in API catalog needs Finnish translations

### ISSUE THREAD

**Issue by Nazarah** [Digipalvelutehdas/APIKA#337]
![image](https://cloud.githubusercontent.com/assets/17976243/22498444/2bab81ac-e861-11e6-9c72-94e22f8f8ff0.png)

![image](https://cloud.githubusercontent.com/assets/17976243/22498472/46154140-e861-11e6-9a06-6a166012ffb3.png)

**Comment by marla-singer** [comment]
@bajiat Verified it on nightly, it is reproduced

**Comment by bajiat** [comment]
This issue was moved to apinf/platform#2046
