### ISSUE TITLE
"Documentation link" label doesn't have translation

### ISSUE THREAD

**Issue by marla-singer** [Digipalvelutehdas/APIKA#342]
Another items without translation
- [x] API profile -> Documentations Tab -> title of popover
![2017-02-01 18 35 49](https://cloud.githubusercontent.com/assets/20643403/22513492/77e87bdc-e8ad-11e6-810a-8f51472c2f3d.png)
- [x] API profile -> Documentations Tab -> Manage dialog -> "Documentation link" label
![joxi_screenshot_1486020841824](https://cloud.githubusercontent.com/assets/20643403/22540784/534f81b8-e933-11e6-8de8-3235c183ccc0.png)

**Comment by marla-singer** [comment]
- [x] API profile -> Documentations Tab -> Manage dialog -> "Documentation link" label
![joxi_screenshot_1486020841824](https://cloud.githubusercontent.com/assets/20643403/22540784/534f81b8-e933-11e6-8de8-3235c183ccc0.png)

**Comment by saralavanip** [comment]
@bajiat , verified this resolved issue on https://staging.apinf.io v 0.40.0. 

Findings:  
- Documentation->Manage->Text field title is untranslated  :  'Documentation link'   
- Documentation->'Generate SDK' dialog -> untranslated text :  'Select language' , 'Download' 

Screenshots: 
![doc_link_title_text](https://cloud.githubusercontent.com/assets/13309358/22742943/3512f458-ee21-11e6-8c7c-ed42ae0072a2.PNG)   
![suomi_sdk_gen_dialog_box](https://cloud.githubusercontent.com/assets/13309358/22742961/44e15a14-ee21-11e6-80f2-e87c51ad9f52.PNG)

**Comment by saralavanip** [comment]
@bajiat , verified this resolved issue on nightly v 0.40.0 and it is not reproducible.  
Screenshot: 
![suomi_view_doc_link_text_resolved_nightly](https://cloud.githubusercontent.com/assets/13309358/22969382/077d6c66-f377-11e6-861f-410d7672d2f0.PNG)
