### ISSUE TITLE
Create schema for organization

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/APIKA#36]
Schema, collection and access control for organization.

# Definition of done
* [x] Collection for organization exists
* [x] Schema for collection exists with minimum following fields
  * [x] name
  * [x] user name (added by or responsible)
  * [x] description
  * [x] contact information (contact person, email, phone, organization web page)
* [x] Access control
  * [x] Admin can add an organization, edit and delete.

Open issue: How can someone (other than admin) become a manager for an organization?

Note: logo is moved to task #43.

**Comment by frenchbread** [comment]
Interested

**Comment by bajiat** [comment]
Can you give an estimate?

**Comment by frenchbread** [comment]
@bajiat Updated.

**Comment by Nazarah** [comment]
@bajiat what information would be included in the access control field? 
* people who would be part of the organization? (do they need to have APIKA account? or email address would be used?)
* Visibility of an organization? (Public/Visible to specific audience group? Private?)

**Comment by bajiat** [comment]
@Nazarah Access control is not a field. It was mentioned for the purpose of reminding the developer that it is necessary to handle permission in the database level.

I think that at least for now that all organizations are public, since the purpose of the organization page is to promote the APIs of that organization. @kyyberi Is this the right assumption?

**Comment by bajiat** [comment]
@brylie Please check the definition of done.

**Comment by bajiat** [comment]
@kyyberi Who should be able to add organizations? Any APIKA user or only admin users?

**Comment by kyyberi** [comment]
I suggest that in the future major questions to PO are discussed in weekly meeting. I don't have now time to follow github so intensively.
