### ISSUE TITLE
UI for adding an organization

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/APIKA#37]
Implement a form for adding an organization. See issue #36 for the fields.

# Definition of done
* [x] Admin can see an option to add an organization.
* [x] Form for adding an organization exists.
* [x] When the form is saved, the data is stored in Organization collection.

# Wireframe

![addui](https://cloud.githubusercontent.com/assets/17976243/20525273/4e1dfc1e-b0c7-11e6-8b2a-aeac09622e52.png)

**Comment by frenchbread** [comment]
Interested

**Comment by Nazarah** [comment]
What fields should we considers in this form?

**Comment by Nazarah** [comment]
# User Flow:

* User is not logged in, but wishes to add an organization -> clicks link from topbar menu -> gets redirected to login/signup page
* User is logged in and at any page in APIKA -> clicks link from topbar menu -> gets redirected to Add organization form

# Open question:
* Are we thinking of adding quick link/ button to Add an API/Organization apart from topbar menu?
* Is any user is allowed to add an organization? or users with specific roles will have that privilege?
* If one user is already an owner of an organization, would he be able to add a second one?

**Comment by Nazarah** [comment]
@frenchbread I designed this wireframe for the Add Organization UI. Give me your feedback about this.
The Add Organization UI can be accessed from TopBar
The form contains all the fields that were described in the Organization Schema #36 
I resused the "upload logo" feature from APINF branding.
I am not yet sure about the access control in organization, but still added the visibility features from API profile.
![addui](https://cloud.githubusercontent.com/assets/17976243/20480979/7c2c154e-afed-11e6-90e6-5e30ce333e02.png)

**Comment by bajiat** [comment]
@Nazarah Take out the Access control. Add organization button should not be in top bar, it could be only in Organization catalog. Add a field for organization URL. 

Created by / Owner field: We'll make a decision on this when we find out who should be able to add organizations.

**Comment by bajiat** [comment]
@brylie Please check definition of done

**Comment by Nazarah** [comment]
@bajiat modified the wireframe as per feedback. Keeping a link at the top to show from where the Add Organization button can be accessed.
![addui](https://cloud.githubusercontent.com/assets/17976243/20482132/84a0de48-aff3-11e6-9261-5e9f3d7728e2.png)

**Comment by frenchbread** [comment]
@Nazarah Thanks for wireframes. 

As @bajiat mentioned, access control should be handled on database level, so it should not be represented somewhere in the schema. I think the last one is what is needed. 

Also as a little enhancement in the future, we could combine, "Add API" and "Add organization" similarly to how Github does it.

**Comment by brylie** [comment]
@bajiat the definition of done looks good. Is it only Admin users who can add organizations?

**Comment by bajiat** [comment]
@brylie I have posted a question about this in #36?

**Comment by frenchbread** [comment]
@brylie @bajiat I currently did it so that only admins can add organizations. And only admins WHO added organizations can edit & remove them. If something will change, we can patch update with separate issue.
