### ISSUE TITLE
Basic UI for viewing organization

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/APIKA#38]
The organization page will eventually be used by organizations to promote their APIs and for users to be able to filter their APIs by lifecycle stage. Start developing the page keeping in mind that the features listed above will have to fit in to the page later.

# Definition of done
* [x] There is a route for single organization.
* [x] There is a view for a single organization that contains
  * [x] name
  * [x] description
  * [x] organization URL
  * [x] contact person with email and phone number

Note: logo has been moved to task #43.

# Wireframe

added part of design for this specific task
![organizationprofile3](https://cloud.githubusercontent.com/assets/17976243/20708629/808dcac2-b639-11e6-90e6-e7ff72698945.png)

**Comment by frenchbread** [comment]
Interested

**Comment by Nazarah** [comment]
Here are some ideas that were made with low fidelity wireframes

1. Organization catalog can be accessed form Catalog menu in topbar
![landingpagea2](https://cloud.githubusercontent.com/assets/17976243/20515984/c5e01b36-b09c-11e6-96c1-d94bcd95c6fc.png)

2. catalog can have both card view and tabular view.
Card of an organization can contain Name, logo, owner's name, description, creation date and overview info about no. of APIs and bookmark link.
Add organization link may be accessed from this page and only APIKA admin might have the visibilty of this button.
![organizationcatalog](https://cloud.githubusercontent.com/assets/17976243/20516050/302c4744-b09d-11e6-8c0d-f196e1ec40c4.png)

3. On clicking a card, a modal would give additional information about no. of peoples in the organization, star rating, and 5 most popular APIS hosted under the organization. from that modal, user can either go to organization profile or to any of the featured API's profile.
![organizationcatalog2](https://cloud.githubusercontent.com/assets/17976243/20516646/19b6900c-b0a0-11e6-888a-6f13b9fe6adb.png)

**Comment by Nazarah** [comment]
Some low fidelity design ideas for organization view:

1. Top part of organization profile shows logo, organization name, owner, option to bookmark and star rating (if preferred). 
Owner of an organization can decide whether or not to make the organization public/private/accessible to specific people in APIKA
Details tab of organization shows description, url to organization page, contact person's information (name, phone, email) and APIs hosted.
![organizationprofile1](https://cloud.githubusercontent.com/assets/17976243/20517583/698d16c4-b0a4-11e6-9f9b-8862ca900b33.png)

2. People tab shows contact information and designations of people belonging to that organization, Owner of an organization can add/modify the list.
![organizationprofile2](https://cloud.githubusercontent.com/assets/17976243/20517636/a957592c-b0a4-11e6-9865-db718d9e6510.png)

3. Settings tab of organization can be used to control access, manage API set, deleting organization, etc.
(need other lists of control if they are to be added in this tab)
![organizationprofile3](https://cloud.githubusercontent.com/assets/17976243/20517908/e30b7c74-b0a5-11e6-9b07-2b3490e19485.png)

**Comment by Nazarah** [comment]
@nnn as discussed earlier, added wireframe specific to this task.
