### ISSUE TITLE
Add organization logo

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/APIKA#43]
Organizations should be able to add their logo. The logo will be displayed in Organization page and in Organization catalog.

# Definition of done
* [ ] Button for adding a logo exists in Add organization view.
* [x] There is a collection for storing the logo.
* [x] Logo is displayed on single organization page.

# Wireframe
In Add Organization form
![addui](https://cloud.githubusercontent.com/assets/17976243/20515208/27f68a7a-b099-11e6-8ca2-32972d9096fb.png)

After uploading a logo
![addui2](https://cloud.githubusercontent.com/assets/17976243/20515216/2e4c0ad0-b099-11e6-8e67-50442c7f7886.png)

In card view (if implemented)
![organizationcard](https://cloud.githubusercontent.com/assets/17976243/20515271/8012681e-b099-11e6-8f59-bc1d2a05b0ff.png)

In organization view, the icon would appear like this:
![organizationprofile3](https://cloud.githubusercontent.com/assets/17976243/20879429/6f4ea3f6-badc-11e6-8d22-c0688ec4e444.png)

**Comment by jykae** [comment]
It would be possibly good to make upload template/component that could take things that change dynamically as parameters, we seem to have pretty much copy/paste code wherever we upload images.

**Comment by jykae** [comment]
@Nazarah uploading organization logo in "add organization" form causes problem when trying to attach id to organization object that doesnt yet exist. 
Discussed briefly with @brylie that upload would be easier to attach to "single organization view" after the organization is added, and user is redirected to newly created organization page.

**Comment by marla-singer** [comment]
@jykae Maybe we can move uploading logo on Settings page? As we have for API page

**Comment by brylie** [comment]
Jep. We can also show an upload modal dialogue when clicking on the logo or logo placeholder. E.g. when a manager or admin is viewing the Organization page, there can be a link 'edit logo' that opens a modal dialogue.

**Comment by jykae** [comment]
@marla-singer @brylie Yep, I viewed https://github.com/Digipalvelutehdas/APIKA/issues/38
Issue descriptions/wireframes were bit differentiating.
@nnn seems to be working initial structure for view page

**Comment by Nazarah** [comment]
For the time being, in organization view, the logo should show a camera icon for editing purpose when mouse is hovered upon it. On clicking the icon, image browser should open.
This should be changed as soon as organization view has a settings page.
then uploading/changing logo should be done from there.
