### ISSUE TITLE
Design/implement Dashboard loading state notification for end user

### ISSUE THREAD

**Issue by brylie** [Digipalvelutehdas/APIKA#50]
When the Dashboard is retrieving data, the end user may be unaware that anything is happening. In order for the user to understand that something is happening, we need to show some loading indicator. The previous loading indicator code was removed as part of a refactor.

**Comment by frenchbread** [comment]
Interested

**Comment by brylie** [comment]
Thanks for taking this task @frenchbread.

Previously, we were using imperative code wrapped within other functions, which made it difficult to keep track of what the code was doing with so many parts. Lets try to use declarative code where possible, e.g. template helpers that observe the state of `chartData`.

**Comment by frenchbread** [comment]
@brylie Agreed, previous solution what a bit messy.
