### ISSUE TITLE
Dashboard date picker issues

### ISSUE THREAD

**Issue by jykae** [Digipalvelutehdas/APIKA#56]
Found in PR review #54 

Notes about date picker
- does not validate range, "To" date can be before "From" date 
- on page refresh date parameters disappear
<img width="1025" alt="nayttokuva 2016-11-28 kello 12 32 46" src="https://cloud.githubusercontent.com/assets/293452/20665081/d67bc30e-b566-11e6-91be-efab1c05dc6d.png">

**Comment by brylie** [comment]
I have fixed the first issue, by linking the from and to fields together.

The second issue only happens when the current date is selected, and is a default behavior of the Bootstrap datepicker.
