### ISSUE TITLE
Ensure dashboard renders charts with ElasticSearch query results

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/APIKA#61]
Currently, the dashboard charts are not being rendered with data, when API backend has been selected from the Select API list.

# General design
![screenshot_20161129_113533](https://cloud.githubusercontent.com/assets/17307/20704451/f91cc400-b627-11e6-84c1-18587800df11.png)

The code design **might** follow this flow:

1. user selects an API from the list
2. `getProxyData` is called with the selected `backendId` and Dashboard query parameters (timeframe, granularity)
    -  on the server, the `getProxyData` method fetches the proxy document, and calls `getElasticData` with the `proxyId`
3. `getElasticData` 
    1. gets the proxy document (URL, type, etc), 
    2. constructs the Elasticsearch query object, and 
    3. makes the HTTP request, 
    4. throw an error if needed
    5. return response data to the client

# Definition of done
* [x] When selecting API backend, ElasticSearch query is made on the server to the right proxy.
* [x] The result of the query is passed to the client.
* [x] Dashboard charts update with the received data.
* [x] Dashboard charts show only data for the selected API.

Related to #50.

**Comment by bajiat** [comment]
@brylie Please add your sketch on architecture.

**Comment by bajiat** [comment]
@marla-singer This is continuation to your work on https://github.com/apinf/platform/issues/1872. Focus on this first, getting the data from ElasticSearch prior to any other dashboard tasks.

**Comment by marla-singer** [comment]
@brylie @bajiat Now develop branch has implementation of point "Dashboard charts show only data for the selected API" and other points.
In this issue I have to refactor code of Elastic Search logic?

**Comment by bajiat** [comment]
@marla-singer We think that the ElasticSearch logic needs some attention. 

What is your estimate for completion?

**Comment by marla-singer** [comment]
@bajiat Estimate is 2 days, I'm already working on it
