### ISSUE TITLE
Connecting APIs to an organization

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/APIKA#73]
Add API form should have a field for organizations that allows to select one organization. (For Nazia to consider: Or should this only in API settings? In addition to wireframe, consider the user flows for connecting the APIs)

# Definition of done
* [x] API schema contains foreign key for organization
* [x] Owner can select one organization either in Add API form or in Settings tab in API profile (or both)
* [x] It is optional to connect API to organization
* [x] Only admin or the organization manager can connect the API to an organization

Open issue: user permissions. Is connecting allowed only for admins and organization managers?

# Wireframes
(courtesy to @marla-singer )
1. API owner can associate the API to an organization (from the list of existing dropdowns) when s/he is adding an API
![addapiconnectorganization](https://cloud.githubusercontent.com/assets/17976243/20959278/d8f9279a-bc62-11e6-9446-8078cbffc56b.png)

2. The organization can also be changed or removed from API profile settings tab. Help text would make API owner aware about the results of disconnecting the API from an Organization
(courtesy to @marla-singer )
![addapisettingsorganization](https://cloud.githubusercontent.com/assets/17976243/20959351/31fb0692-bc63-11e6-9125-9cd70975a3d3.png)

3. Information about an organization's Association would appear in the API Metadata Tab
![apimetadata](https://cloud.githubusercontent.com/assets/17976243/20959515/01415794-bc64-11e6-946a-98fec22d47f8.png)

**Comment by Nazarah** [comment]
It is better to keep the option of adding an organization both in Add API form and API settings tab.
In Add API form, this field should not be mandatory.

@bajiat need clarification: does connecting an API to an organization means from an organization page, you would be able to make calls to that API and/or access its documentation? Please kindly explain.

Open question: suppose API owner has an API private, but that is visible to admin and organization managers. Now would the Admin/ organization managers be able to connect the API to the organization?

**Comment by marla-singer** [comment]
@bajiat Interested

**Comment by bajiat** [comment]
@Nazarah Connecting an API to an organization makes the API visible in the organization page, i.e. there is a catalog of APIs on the organization page. See  #74.  Later, we should also be developing support for API managers for an organization, see #24.

**Comment by bajiat** [comment]
@marla-singer Please estimate the task

**Comment by marla-singer** [comment]
@bajiat Estimate is 3 days

**Comment by Nazarah** [comment]
@marla-singer : please add a help text under  Connect API to an Organization.
"You can connect your API to an organization. Organization Manager will review your request. If approved, your API should appear in the Organization profile. You can also change the organization and disconnect your API from any organization."

**Comment by Nazarah** [comment]
@marla-singer : have made changes in the wireframes.
You may need to remove Connect API to an Organization field from Add API forms.
