### ISSUE TITLE
Showing organization APIs on organization page

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/APIKA#74]
# User story
> As an organization manager,
I want to show my organization's APIs on the organization page
so that I can promote them.

# Definition of done
* [x] Organization page contains an API catalog that lists only APIs connected to that organization
* [x] The catalog only shows API cards, i.e. there is no option to toggle to table

# Wireframe

1. new API card design
It includes new label to indicate what lifecycle phase the API is currently in.
![cardapi](https://cloud.githubusercontent.com/assets/17976243/20886887/e47778fa-bb00-11e6-869a-8d9e86763f33.png)

2. This is how APIs appear in a organization view
In Organization profile, members within an organization (future option) as well as APIs appear as cards/blocks.
(with future implementation works) APIs can be filtered by clicking of labels (quick filters: visibility, API Lifecycle) or accessing the filter menu.
![organizationprofile3](https://cloud.githubusercontent.com/assets/17976243/20967458/4980b864-bc88-11e6-85ad-6eba9c9b692c.png)
If an organization has a lot of APIs that can be seen in a single view and have to browse downwards for viewing them, we can implement infinite scrolling and option to go back on top

open question: should we show settings option in a modal or a tabview (working on the wireframes)

**Comment by marla-singer** [comment]
@bajiat Interested

**Comment by marla-singer** [comment]
@bajiat Estimate is 3 days.

**Comment by Nazarah** [comment]
Have started adding wireframes, would finish it up by wednesday.
