### ISSUE TITLE
Show lifecycle status for API

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/APIKA#76]
# User story
> As an API user
I want to be able to see the lifecycle status of an API
so that I can determine how safe it is to start using an API

# Definition of done
* [ ] Once owner has added a lifecycle status for API, it needs to be shown in
  * [ ] Catalog card view
  * [ ] Catalog table view
  * [x] API profile

# Wireframe
1. API cards showing 5 lifecycle statuses:
![cardapidesign](https://cloud.githubusercontent.com/assets/17976243/21179716/f43d8cbc-c1fd-11e6-84b4-3f3204747bec.png)
![cardapidevelopment](https://cloud.githubusercontent.com/assets/17976243/21179722/fb5464da-c1fd-11e6-8db0-df5a1558ee3c.png)
![cardapitesting](https://cloud.githubusercontent.com/assets/17976243/21179724/ffccfb4e-c1fd-11e6-88c8-db7f134f8ec0.png)
![cardapiproduction](https://cloud.githubusercontent.com/assets/17976243/21179729/0508428a-c1fe-11e6-93a1-1c1dd2c5bc09.png)
![cardapideprecated](https://cloud.githubusercontent.com/assets/17976243/21538130/60303992-cda2-11e6-8151-f415d9a8bd06.png)

from @bajiat 's feedback, we should replace the tag for "private" APIs. The reason is that an API may or may not be private, but it would always have a lifecycle status. so that tag should be placed first in API card

2. API lifecycle status can be seen as colored labels in both card and table view.
From both view, the APIs can be filtered by one/more lifecycle statuses.
[future implementation suggestion: filter by private and public APIs]

![apicatalognew](https://cloud.githubusercontent.com/assets/17976243/21181244/a29b43ce-c205-11e6-9a70-543532e0bf10.png)

3. In API profile, the status appears on top of the page.
On transiting from one status to another, the time of change and transit from status appears as information (alt. can also be shown as tooltip on hover)

![lifecycleapiprofile3](https://cloud.githubusercontent.com/assets/17976243/21181292/d82e907c-c205-11e6-8784-6ca528bec3cf.png)

**Comment by bajiat** [comment]
<span class="label label-default">Default</span> use for undefined
<span class="label label-primary">Primary</span> use for development
<span class="label label-success">Success</span> use for production
<span class="label label-info">Info</span> use for design
<span class="label label-warning">Warning</span> use for testing
<span class="label label-danger">Danger</span> use for deprecated

**Comment by brylie** [comment]
Follow up task to [filter API catalog by Lifecycle Status](https://github.com/Digipalvelutehdas/APIKA/issues/170)

**Comment by Nazarah** [comment]
@brylie based on @bajiat 's feedback, am changing the color of "Deprecated" Status to Red. Red would work as a caution to API consumer, so that they use this API in their own risk. The status "Unknown" can be shown in grey.
Am updating other lifecycle wireframes in related issues.
