### ISSUE TITLE
wireframe for "Connecting APIs to an organization"

### ISSUE THREAD

**Issue by Nazarah** [Digipalvelutehdas/APIKA#79]
#73

**Comment by Nazarah** [comment]
Wireframes have been added to issue #73.
Dasha have shown me the new added field for connecting an organization with an API and how to change it from API settings tab as well.
I gave my feedback about showing showing organization information in the API metadata tab.

**Comment by bajiat** [comment]
This was discussed with @kyyberi and the workflow for adding APIs to organization should go like this:
- API owner can suggest APIs to an organization
- organization manager can approve or reject. If approved, the API will be connected to the organization. As a result, the API will be shown in the organization page. 

Add API form should not contain the possibility to connect to organization, it should only be in API settings.

**Comment by Nazarah** [comment]
@bajiat have made the suggested changes in the wireframes and added them to the main issue #73 
Would you reopen the issue?

**Comment by bajiat** [comment]
@Nazarah: 
- Add a workflow: API owner suggests APIs, organization manager approves or rejects. Only after that the info about organization can appear on API profile.
- Consider how to show to owner that this is a suggestion that is pending approval (S alert, other notification, the title of field in API settings)

**Comment by Nazarah** [comment]
@bajiat suggested modifications are added to the original issue.
