### ISSUE TITLE
Filter APIs in organisation view

### ISSUE THREAD

**Issue by kyyberi** [Digipalvelutehdas/APIKA#8]
As API manager of given organisation I want to filter listing of APIs on my organisation's view. Some are Design phase, some development, some production and some retired.

# Wireframe

I made some sketches about how filtering option may work in Organization page.
1. The API view of an organization profile would have a filtering option at the right most side
![altorganizationprofileapiview](https://cloud.githubusercontent.com/assets/17976243/21047917/2d93333c-be15-11e6-8954-f0ffa448d517.png)

2. User would be able to filter this view based on API lifecycle status (and if implemented in future: API visibility)
![altorganizationprofileapifilter](https://cloud.githubusercontent.com/assets/17976243/21047942/487f54aa-be15-11e6-9f0d-67b5be591c8e.png)

![altorganizationprofileapifilter2](https://cloud.githubusercontent.com/assets/17976243/21047943/488009ae-be15-11e6-8a75-ff8465d5ee3c.png)

3. In the filtered view, no. of APIs appearing (for the filtered result) as well as filtering criteria text should appear. There would be option beside the text to clear the filtered result.
![altorganizationprofileapifilter3](https://cloud.githubusercontent.com/assets/17976243/21047965/6d052bba-be15-11e6-8e04-001b27878d22.png)

4. One additional feature that can be considered is that, since API cards have tags "Private" (if the API is private) and "Lifecycles", clicking on a tag would automatically display the content filtered accordingly. For example, if clicked on "Design" tag, the view would show only APIs that are in "Design" phase. Afterwards, on opening the filter menu, user can see on which categories the result has been filtered.

# Related issue(s)
- [Filter API Catalog by Lifecycle Status](https://github.com/Digipalvelutehdas/APIKA/issues/170)

**Comment by philippeluickx** [comment]
Can an API have multiple organizations linked?

**Comment by Nazarah** [comment]
Here is an idea about how APIs can be filtered in organization view.
In organization catalogue, you can filter organizations based on the life cycle phase of an API and tags of API.
You can select multiple option from dropdown in the filtering.
We need to think about the implementation of this filtering function (mainly the AND/OR logic to return filtered results)
![organizationcatalog3](https://cloud.githubusercontent.com/assets/17976243/20381320/a27b16b4-acaf-11e6-9e86-a1f6a3f7b1f2.png)

**Comment by bajiat** [comment]
@nnn Would you be interested in this?

**Comment by brylie** [comment]
> Can an API have multiple organizations linked?

@philippeluickx right now we are considering that an API should only be related to one organization.

**Comment by philippeluickx** [comment]
Ok, clear!

**Comment by bajiat** [comment]
This needs to be a component that can be shared between API Catalog and Organization page. URL parameter for filter also needed. Filtering by one lifecycle status at a time is enough. Multiple selection could be an enhancement for later.

**Comment by bajiat** [comment]
@marla-singer Would you be interested in this task? Can you please estimate?

**Comment by marla-singer** [comment]
@bajiat Yep, i'm interesting. Estimate is 5 days. Need to know some information.
How will this filter be integrated with current filtering in API catalog?
Current filter in red frame:
![joxi_screenshot_1483951051278](https://cloud.githubusercontent.com/assets/20643403/21760833/289361f0-d660-11e6-81c3-a1bc250c1f8d.png)

**Comment by bajiat** [comment]
Add a select menu for the lifecycle status. When the value in the select menu gets selected, put the value in the URL as a parameter. Filter the page accordingly.

See also my comment above about reusable component.

@Nazarah How does adding a select menu sound to you?
