### ISSUE TITLE
wireframe for "Allow owner to define lifecycle status for an API"

### ISSUE THREAD

**Issue by Nazarah** [Digipalvelutehdas/APIKA#81]
#75

**Comment by Nazarah** [comment]
wireframes added to issue #75

**Comment by bajiat** [comment]
I think we would need to check from @kyyberi whether adding the lifecycle status should be mandatory. I can do that in the next status meeting.

**Comment by bajiat** [comment]
@Nazarah Move the place of the tag and drop down menu. It should be in the same area as private tag or rather next to it.

**Comment by bajiat** [comment]
@Nazarah 
Modified suggestion: Adding the status should not be mandatory. Lifecycle status is also not included in the Add API form. On the API profile, there is an undefined/unknown status shown until API owner selects a lifecycle status. Once manager defines the lifecycle, it should not be possible to select undefined/unknown anymore.

**Comment by Nazarah** [comment]
Changes have been made to the wireframes. They are now added to the main issue. #75
