### ISSUE TITLE
wireframe for "Show lifecycle status for API"

### ISSUE THREAD

**Issue by Nazarah** [Digipalvelutehdas/APIKA#82]
#76

**Comment by Nazarah** [comment]
wireframes added to issue #76

**Comment by bajiat** [comment]
This is probably nitpicking, but maybe it is best to show the API cards in #76 with the in the order that actually follows the API lifecycle: design, development, testing, production, deprecated.

Some of you wireframes contain other words for the tags than the ones mentioned in the the issue, e.g. Design and prototyping. Please modify.

Like the idea of showing the time when the status was changed.

**Comment by bajiat** [comment]
I'm not sure there is a need to filter according to visibility setting. That has not been requested for APIKA.

**Comment by Nazarah** [comment]
@bajiat have an open question: If API owner selects any of the statuses apart from "Undefined" would it be possible for reselecting that status anymore? or once you have selected any of the predefined status, the dropmenu should no longer show "Undefined" tag?

**Comment by bajiat** [comment]
@Nazarah: The confirmed list for lifecycle status is design, development, testing, production, deprecated. Please modify wireframes accordingly

**Comment by Nazarah** [comment]
@bajiat changes have been made to the wireframes. They are added in the main issue #76
