### ISSUE TITLE
Unified LAF for API view and Organization view

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/APIKA#83]
This is a wireframe issue only.

Experiment with block design on API view and Organization view. Low fidelity wireframe is sufficient for starters. Keep also the frontpage in mind. Minimise tabs. See feedback from issues #10 and #11.

# Wireframes

I have two type of designs in my mind.
Any of the design can be incorporated for both Organization and API Profiles.
I'll design Organization profile with one design pattern and API profile with another design pattern

* Organization Profile

The design is based on the way APINF project page looks and functions. http://apinf.org/
There are two main sections: APIs and Settings.
User can see his current section at top right side, can click on one section to navigate there or do the same action by up/down scrolling

1. API View:
Connected APIs would appear as cards in this view.
An API manager, who is also the manager of the organization can connect his/her managed APIs to an organization by clicking "Connect API to Organization" button 
Users can filter the APIs by lifecycle phase and public/private visibility (if implemented)

![altorganizationprofile3](https://cloud.githubusercontent.com/assets/17976243/21385534/8d77c13a-c777-11e6-9946-a312a56d966d.png)

![altorganizationprofileapifilter](https://cloud.githubusercontent.com/assets/17976243/21385547/9655ff2e-c777-11e6-9d0e-ad3017bb0edb.png)

![altorganizationprofileapifilter2](https://cloud.githubusercontent.com/assets/17976243/21385554/9fa28610-c777-11e6-88b4-4b9f9aa824f9.png)

![altorganizationprofileapifilter3](https://cloud.githubusercontent.com/assets/17976243/21385567/aa7c8180-c777-11e6-9939-6c0bae820f27.png)

One additional feature that can be considered is that, since API cards have tags "Private" (if the API is private) and "Lifecycles", clicking on a tag would automatically display the content filtered accordingly. For example, if clicked on "Design" tag, the view would show only APIs that are in "Design" phase. Afterwards, on opening the filter menu, user can see on which categories the result has been filtered.

2. Settings view
Here, manager can edit section general information, contact details, add  additional managers, connect APIs to organization and delete. 
![altorganizationprofilesettings3](https://cloud.githubusercontent.com/assets/17976243/21386189/52c08cae-c77a-11e6-9542-3b5e4ebcfeaf.png)

An alternate idea can be to give edit option to change general information and contact details from top side of organization profile. On mouse hover, an edit button will appear. Clicking the button would make all the fields (i.e. Name, description, url, logo, contact information) editable.
![contactpersonsettings](https://cloud.githubusercontent.com/assets/17976243/21386342/06987da4-c77b-11e6-9049-d749f87264ec.png)

![contactpersonsettings2](https://cloud.githubusercontent.com/assets/17976243/21386349/0e60c3de-c77b-11e6-964d-bdb93ef06d11.png)

(here, the wireframe shows only for contact person, but this can be implemented for other contents. Dipor has similar design)

**Comment by bajiat** [comment]
@Nazarah Please note that organization members has not been requested as a feature for APIKA.

**Comment by Nazarah** [comment]
The 2nd design has been made for API profile and can also b implemented for organization profile as well.
Requirements if issues #10 and #11 has been kept in mind while designing.
The view gets rendered depending on the number of cards and their sizes.
Cards can be moved along the page (if possible to implement)
The design is based on Bootstrap card components: https://v4-alpha.getbootstrap.com/components/card/

1. the API profile is now divided into 4 sections: Overview (top portion), General, Settings and Proxy.
In top part, there will be information about Name, logo, owner, organization (if connected), status (circle indicating API's health and tooltip giving information about average response time), lifecycle status tag and change information, Private tag (if made private) and options for star rating, bookmark, getting API key and quick tour options.
![mockup_4](https://cloud.githubusercontent.com/assets/17976243/21585861/10361286-d0d1-11e6-903c-9af08a20efd2.png)

2. Now there is only three tabs/sections about General API information, Settings and Proxy Settings.
The sections can be browsed either with mouse click or scrolling down the page.

![apiprofile1](https://cloud.githubusercontent.com/assets/17976243/21586015/e5bbc976-d0d3-11e6-9011-471d1952dbfc.png)


The general view now contains information about:
2.1 Details (Description, URL and Instructions to make API calls)
![mockup](https://cloud.githubusercontent.com/assets/17976243/21586055/911562b4-d0d4-11e6-8fe4-3a5605e250ad.png)

card style: https://v4-alpha.getbootstrap.com/components/card/#header-nav

2.2 API documentation (Swagger view with options to download documentation, Managing available methods and providing link to live documentation)
![mockup_5](https://cloud.githubusercontent.com/assets/17976243/21586234/3c3b794c-d0d7-11e6-96c1-004effdd052f.png)

on clicking manage button on the card, dialogue would appear in front view to add link to live documentation link, making methods available and download the documentation
![image](https://cloud.githubusercontent.com/assets/17976243/21586258/9e497666-d0d7-11e6-8285-4cca7d487c29.png)
more about card content: https://v4-alpha.getbootstrap.com/components/card/#content-types

2.3 API Metadata: Organization (if connected), Contact information and Service
![mockup_2](https://cloud.githubusercontent.com/assets/17976243/21586339/9567b368-d0d8-11e6-97b9-038ffa2844ae.png)
card design: https://v4-alpha.getbootstrap.com/components/card/#header-nav

2.4 Export options for API and Proxy configuration in json and yaml format
![mockup_6](https://cloud.githubusercontent.com/assets/17976243/21586639/e179ca90-d0db-11e6-8c18-96723d4951b1.png)
card design: https://v4-alpha.getbootstrap.com/components/card/#header-nav

2.5 Option to download code snippets in languages made available by owner
![mockup_7](https://cloud.githubusercontent.com/assets/17976243/21586692/4cc1a872-d0dc-11e6-952a-18a24576044b.png)
card style: https://v4-alpha.getbootstrap.com/components/card/#sizing

2.6 Option to add backlogs. Here a card will be used to open the Add Backlog dialogue/form. Added backlogs would appear as a group of cards. each backlog card will also show the priority of the backlog.
![mockup_8](https://cloud.githubusercontent.com/assets/17976243/21586887/92d95786-d0de-11e6-89c5-c90c28e8eef4.png)
card style: https://v4-alpha.getbootstrap.com/components/card/#groups

2.7 Ombed content that API owner uploads. Here a card will be used to open the Add Ombed content dialogue/form.The content cards appear as group with preview about the content and an link to navigate to the main content.
open question: should there be restrictions about the number of content cards to be displayed in the general view? what about seeing past entries?

![mockup_9](https://cloud.githubusercontent.com/assets/17976243/21587025/25d2bca2-d0e0-11e6-9b72-5d680262a736.png)
card style: https://v4-alpha.getbootstrap.com/components/card/#groups

2.7 Option to provide feedback. Here a card will be used to open the Add Feedback content dialogue/form.The feedback cards appear as group and shows with a tag if it is a feedback, feature request or error report. There would be also option to give like/dislike to a single feedback.
![mockup_10](https://cloud.githubusercontent.com/assets/17976243/21587825/3c2057a4-d0e9-11e6-82fd-189637a86ec8.png)
card style: https://v4-alpha.getbootstrap.com/components/card/#groups


2.8 There would be cards to show most recent 5 github issues related to the API. The cards will show title, creation time, creator's information and a link to view the issue in github. In addition, there would be a link to visit the main repository and the related issues in GitHub. The cards would appear as groups.
card style: https://v4-alpha.getbootstrap.com/components/card/#groups
![mockup_11](https://cloud.githubusercontent.com/assets/17976243/21587908/ef6fa238-d0e9-11e6-8364-0b1f6814a4c9.png)

**Comment by Nazarah** [comment]
Since the general view is the prime concern for API's consumer's attention, we can keep the look and feel of the settings and proxy tab as it is. Since it is upto the API manager and Administrator to change the settings, the current look and feel makes it simple, familiar and easy to use.

**Comment by Nazarah** [comment]
an alternet suggestion for cards with navigation bar is the following design.
Here, information can be added as a list group
![mockup_12](https://cloud.githubusercontent.com/assets/17976243/21589118/231e8696-d0f7-11e6-88ff-9952b9a15315.png)
The design component in card: https://v4-alpha.getbootstrap.com/components/card/#content-types

**Comment by Nazarah** [comment]
One more design idea is that the cards that have some tags attach to it (e.g. for Feedback cards with "Feature Request", "Feedback" and "Error Report"), clicking on a Tag will render the view with cards of that specific tags. 
E.g. clicking a feedback card with "Feature Request" tag would leave the view with only feedback cards of that type. The primary card of adding a feedback would always remain with the card groups.
There will be an option at the top part to clear the filtered view.

**Comment by bajiat** [comment]
@Nazarah I really like the second design for the API profile. Not sure how it would work for the Organization view, though, since it does not have so many different elements as the API profile. Here are some comments mainly concerning the 2nd design:
- I think it could be quite cumbersome to use the tabs in Details and Metadata - and maybe even difficult to notice them
- Export > this is for owner only. Maybe we could even consider moving export functionality for each of the settings tabs. Just have a button to export the setting they are currently viewing (either Settings or Proxy). How does that sound to you?
- API Content: the button should not be called Add a Blogpost, since it is possible to add/embed videos, presentations and images as well
- What is Live documentation?
- "Backlogs" should not be plural. A backlog is an ordered list of items, e.g. issues, tasks. The individual items are not called backlog.
- We need to consider what we would do, if there is manually added backlog and also a list of Github Issues. Should we only have one area in the UI for backlog and it is either a manually inserted backlog or the Github issue list? I liked the design of the Github issues list with the possibility of seeing more - which probably should open another view or go to Github.
- "Feedbacks" cannot be in plural
- Code snippets: at the moment we are not allowing owners to add code snippets. Instead we have functionality for downloading SDKs based on Swagger (in case owner has uploaded a Swagger file)

**Comment by Nazarah** [comment]
@bajiat thanks for your feedback. Since now the organization profile has API cards as its main view, we can keep it up as it is for the time being. If other functionality of organization appears in future, we can incorporate those as cards similar to that of API profile.

1. We can use a separate car design to show Details and Metadata cards. I have already referred to the following design in my previous comment. This is also supported by BootStrap Cards.
https://cloud.githubusercontent.com/assets/17976243/21589118/231e8696-d0f7-11e6-88ff-9952b9a15315.png

2. Fine with me for moving Export functionality in Settings tab. In current API profile, this is added as a separate tab, so I thought of incorporating the functionality as a separate card.

3. API content: button will be fixed in the main wireframe. How does "Add content" sound?

4. "Live documentation" term was used by Jarkko in #10. it may refer to the swagger documentation hosted in the actual webpage. In current API profile, this possibly refers the link that we share to access swagger documentation.

5. "Backlog" term would be used.

6. Can you please confirm with Jarkko  how does he want the backlog adding functionality? What we can do is that we can have the similar backlog adding Backlog of APInf, only this would automatically create an issue in GitHub. How does it sound to you.

7. "Feedback" term will be used.

8. 'Code snippets" were mentioned by Jarkko at #10. However, we can have the existing functionality of downloading SDK files from Documentation card. Infact in the low fidelity designs, I have included it.

I'll start converting the designs into high fidelity ones. Please feel free to add your suggestions and feedback.

**Comment by bajiat** [comment]
3. "Add content" sounds fine to me.
4. I find "Live documentation" confusing. What does that make Swagger document then? And if you have uploaded the Swagger document to APIKA, why do you want a link to Swagger document on a website? 

Also consider what does entire view looks like, if there is no Swagger document here? What if there is only a link to external documentation available. 

6. I don't think we can assume that all will have a backlog in Github. I think the owners should be able to select whether to show backlog at all and if yes, if it displays a backlog from Github or a backlog they add themselves item by item in Github.

Please consider 4 and 6 before moving onto high fidelity wireframes.

**Comment by philippeluickx** [comment]
My 2 cents:
- Focus on aligning the designs for both API and organization views. They should look exactly the same. Organization has added functionality, which should all be located in the top part (grey part) of the screen.
- Faceted filtering is tricky to get right. One clear rule though is that all filters should be visible at all times. It's not good to hide them behind a click.
- I am not a big fan of having lifecycle as a filter element. 95% of the time the user will want to see the current live API (my assumption) and that's what we should design. I would rather show the other lifecycles in the detailview then.
- In general, we should start with designs that (only) support the common use case. I am totally fine with backlog being Github-only to start with. Once we start getting enough customer requests for adding more options, we should consider.
