### ISSUE TITLE
Create organization catalog

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/APIKA#84]
Create a catalog page for listing the organizations added to the service. Keep the style consistent with the API catalog. Start with the card metaphor.

# Definition of done
* [x] User can go to the organization catalog
* [x] All the organizations are visible on the catalog page
* [x] Organizations use card metaphor similar to API catalog
  * [x] name
  * [x] logo
  * [x] description
* [x] Organization catalog is visible to all users (even unregistered users)

# Wireframes

1. Organization catalog can be accessed from Catalog menu on the topbar
The view consists of organization cards, option to add a new organization (accessible only from this view) and sorting + filtering option (future task?) for the organization view
![organization catalog](https://cloud.githubusercontent.com/assets/17976243/20883754/7272e650-baf0-11e6-8b60-e18b87b7181a.png)

2. This is an organization card
this includes the logo, name (link), owner/contact person name (needs clarification), description and when the organization was added.
For future work, we can show how many APIs are hosted by the organization and an option to bookmark the organization
![cardorganization](https://cloud.githubusercontent.com/assets/17976243/20883789/9c89508c-baf0-11e6-9f87-d0862f2a7028.png)

**Comment by marla-singer** [comment]
@bajiat Interested

**Comment by marla-singer** [comment]
@bajiat Estimate is 2 days

**Comment by marla-singer** [comment]
@bajiat Do I need to do filtering and sorting in this task or it will be another issue for that?

**Comment by Nazarah** [comment]
@bajiat @marla-singer consider the following view
![organizationcatalog2](https://cloud.githubusercontent.com/assets/17976243/20883807/afd513ba-baf0-11e6-8dcf-ba8d562db29d.png)
When you click on an orgzanition card, it gives you a preview window as modal.
This includes the card information as well as additional information like no. of users, most popular APIs (currently 3) and a link to view more APIs that leads to organization profile.
What do you think about incorporating this feature?

**Comment by Nazarah** [comment]
Open question: should we have tabular view for organization catalog as well?
