### ISSUE TITLE
Wireframe for "Create Organization Catalog"

### ISSUE THREAD

**Issue by Nazarah** [Digipalvelutehdas/APIKA#85]
#84

**Comment by Nazarah** [comment]
wireframe added in issue #84

**Comment by bajiat** [comment]
I would suggest that both API Catalog and Organizations would be directly accessible from the top bar. I especially don't want API catalog to be accessible with second selection, it must be directly on the top bar.

**Comment by bajiat** [comment]
Based on discussion with @kyyberi, there is no need to provide bookmarking, but the number of APIs connected to the organization is needed.

**Comment by Nazarah** [comment]
@bajiat @marla-singer based on the feedback from Jarkko, I have modified the wireframes and added them in the original issue #84 
the wireframes now show Organization catalog as a separate menu on top bar
Should you reopen the issue and incorporate the changes?

**Comment by Nazarah** [comment]
Changes have been added to wireframes.
The wireframes are now available on issue #84
