### ISSUE TITLE
Design organization routing with respect to APIs and internal API routes

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/APIKA#86]
Some of the organization views have organization as route, while some have organizations. Pick one of the option for consistency and change all organization routes to match.

# Organizations routes proposal

- `/organizations` - organization catalog
  - `/organizations/< slug >` - single organization view

# Related changes
For consistency, we can consider our routing structure for the following components:
- APIs
- REST API

## Example routing structure
One possible example of backwards incompatible routing changes would be:

- `/apis/` - API catalogue
  - `/apis/< _id >` - Single API profile
  - `/apis/< slug >` - alternative to using ID, if each API has unique URL slug
- `/api/` - routes for internal API

**Comment by brylie** [comment]
Ping @Digipalvelutehdas/apika-tiimi please review the proposal for URL routes. This idea would improve the consistency of our routing and give us room for a simple REST API routing structure.

**Comment by jykae** [comment]
@brylie I think that 's' character difference for REST API base URL is a bit too close for typos.
Above is the reason for choosing base URL /rest-api that is currently used.

Though I am open to change it if I am only one scared for typos :)

**Comment by brylie** [comment]
What could be some possible situations where a typo would cause problems? How much difficulty might they cause?

**Comment by philippeluickx** [comment]
Agreed, most URLs are not typed. Or are you worried for typos in the code?
Another option could be to prefix e.g. /internal/apis

**Comment by bajiat** [comment]
@brylie I'm ok with plural for organizations and apis
