### ISSUE TITLE
Set up email configurations for APIKA

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/APIKA#88]
In order to validate emails, allow users to get a new password to replace a forgotten password and to send messages from contact form, to and from emails are required for APIKA.

# Definition of done
* [x] Add the required SMTP settings to Settings
* [x] Add to and from emails
* [x] Ensure that existing users will not have to validate their emails.

**Comment by jykae** [comment]
@bajiat Checked from mongo that all existing user's have email verified: "true", tried also registering new user, got verification email & using verification link worked.

**Comment by jykae** [comment]
@bajiat Tried also password reset with "Forgot password", notified "Email sent", got email, used link, got redirected to change password, logged in automatically with new password. Logged out & logged in with new password. Worked 10/10.

**Comment by jykae** [comment]
@bajiat Tested also proxy call for Teosto API, works.
