### ISSUE TITLE
Release testing

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/APIKA#89]
Test the new release on staging server. Report any bugs or enhancement needs to [APIKA repository](https://github.com/Digipalvelutehdas/APIKA/issues).

See the new and improved features in the [release notes](https://github.com/apinf/platform/releases)

# Definition of done
* [x] Test any new development
  * [ ]  Admin can add eMQTT as proxy in Proxies
  * [x] UI for adding an organization 
  * [x] UI for viewing organization 
* [x] Test bug fixes for dashboard: #51, #56, #61
* [x] Go through acceptance testing

**Comment by saralavanip** [comment]
- Verified resolved issues #51, #56 and they are not reproducible.
- Reported issue #106

**Comment by bajiat** [comment]
Closing the issue, since testing is completed.
