### ISSUE TITLE
Fix up API card height so that information are not scrambled with each other

### ISSUE THREAD

**Issue by Nazarah** [Digipalvelutehdas/APIKA#94]
![image](https://cloud.githubusercontent.com/assets/17976243/20885384/340edb72-baf9-11e6-8b69-d8281c5679c7.png)

Right now, if an API is made private, then  a label appears in the card view.
This pushes the description field lower, which in turn gets scrambled with Bookmark, Starrating and add date information.
We need labels to show visibility of the API as well as its lifecycle phase (future implementation)
[open questionL Also from organization view, we might need to incorporate card actions]
So suggesting to increase height of the card view, so that information are not scrambled with each other

**Comment by Nazarah** [comment]
closing the issue as works would be done under issue #118

**Comment by bajiat** [comment]
Reopening the issue, since the bug still exists. There could be multiple options to fix it.

<img width="217" alt="api card gets scrambled" src="https://cloud.githubusercontent.com/assets/11626388/21845285/ac3972ec-d7fa-11e6-812a-a2fea917c438.png">

**Comment by marla-singer** [comment]
@bajiat This issue can be resolve in #118

**Comment by bajiat** [comment]
@marla-singer I noticed Nazia's comment, but still wanted to keep the original report.
