### ISSUE TITLE
Update API Umbrella

### ISSUE THREAD

**Issue by bajiat** [Digipalvelutehdas/APIKA#96]
Update umbrella.digipalvelutehdas.fi to the latest Api Umbrella version.

Using the Umbrella deployed to umbrella.digipalvelutehdas.fi allows not changing any API calls that are made to current APIKA version. The Umbrella just needs to be updated.

**Comment by bajiat** [comment]
@shaliko Can you take this task?

**Comment by shaliko** [comment]
@bajiat Sure, just need access to that server.

**Comment by bajiat** [comment]
@shaliko Can I close the issue, since the update has been completed?

**Comment by shaliko** [comment]
Yes, thanks for reminder
